### ISSUE TITLE
为什么在aistudio中无法使用yolov7进行多卡训练，会卡着一直没有训练的log

### ISSUE THREAD

**Issue by wjfwjfwjf** [PaddlePaddle/PaddleYOLO#100]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

为什么在aistudio中无法使用yolov7进行多卡训练，会卡着一直没有训练的log

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov7/yolov7_tiny_300e_coco.yml#L8
第0iter打印了吗？最好提供下截图。可能是还没打印完全，可以调小打印间隔为1， log_iter: 1

**Comment by wjfwjfwjf** [comment]
没有打印第0iter，等了好久了，麻烦在aistudio上跑一下试试？

**Comment by wjfwjfwjf** [comment]
![image](https://user-images.githubusercontent.com/49022937/223911194-86cbabcd-dedf-49d7-a97f-10a8f898c30c.png)

**Comment by nemonameless** [comment]
请先确保paddle安装无误，cuda gcc cudnn等符合机器环境。另外报错请补充下环境信息、版本信息等以便排查谢谢。
yolov7p6_e6过大，确认下显存是否足够，建议换小模型tiny或L训练，或减小bs
