### ISSUE TITLE
训练YOLOv8

### ISSUE THREAD

**Issue by WanShaw** [PaddlePaddle/PaddleYOLO#103]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

想请问一下，什么时候可以实现训练yolov8呢？我觉得pdyolo的实现比官方或者mmyolo更好，所以一直想等着用用！

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
谢谢关注。由于工作安排问题，我们是将YOLOv8的训练实现放到了 [飞桨黑客松论文复现赛](https://github.com/PaddlePaddle/Paddle/issues/51281#detection) 里，具体比赛可看[PaddlePaddle Hackathon 飞桨黑客马拉松第四期](https://aistudio.baidu.com/aistudio/competition/detail/776/0/introduction)。我们也会及时评估选手的进度，必要时辅助选手或自行实现，由于比赛原因预计4月底才可以公布实现。

就当前性能来看，PPYOLOE+ 模型只训80epoch的情况下还是可以略胜YOLOv8的500epoch，你可以训更多epoch试试。

此外PPYOLOE+的小目标、旋转框、密集检测、半监督检测、检测蒸馏、tiny版本、obj365预训练、transformer等超大型backbone、各种人车工业垂类应用都很齐全，欢迎使用。
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe 
https://github.com/PaddlePaddle/PaddleDetection/releases/tag/v2.6.0

**Comment by WanShaw** [comment]
好的，谢谢回复。请问有ppyoloe+直接在coco数据集上的训练日志吗？
还有ppyoloe的+版本，是在论文预印后改动的，我好像没有在issue中发现’在backbone中block分支中增加alpha参数‘的解释，该参数的具体目的，请相关大佬能解释一下吗？这个参数对另一个并行分支进行了加权，而且alpha是可学习的。

**Comment by nemonameless** [comment]
ppyoloe+只要训80epoch相对已经很快了。后面会统一放出来log，都是每10epoch一次eval精度的。
alpha参数就是可学习参数因子，几乎不增加参数量计算量，也不影响速度，但是可以提高mAP，coco上虽不明显，但下游任务业务数据集上提升很明显。

**Comment by WanShaw** [comment]
好的，感谢大佬回答
