### ISSUE TITLE
YoV5训练问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleYOLO#110]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问一下，我用YoloV5训练过程中，想把Epcoh值增加进行，发现训练到300轮之后就自动停止了，请问这是怎么回事呢？如何修改配置文件
![image](https://user-images.githubusercontent.com/87969070/226847654-26719399-f195-4732-90d4-e8101e08a3d9.png)

**Comment by nemonameless** [comment]
请把你的代码改动都发下，以便排查。如报错请按模板提问谢谢
https://github.com/PaddlePaddle/PaddleYOLO/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml

**Comment by Hold-on-li** [comment]
> 请把你的代码改动都发下，以便排查。如报错请按模板提问谢谢 https://github.com/PaddlePaddle/PaddleYOLO/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml

你好，这是我改的配置
![image](https://user-images.githubusercontent.com/87969070/227073288-8849e3d0-4476-428e-81ff-4958aa0c26aa.png)
![image](https://user-images.githubusercontent.com/87969070/227073265-58064510-a869-4297-858a-02117b178ce1.png)

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/configs/yolov5/_base_/yolov5_reader.yml#L4
mosaic_epoch 也需要改为600

**Comment by nemonameless** [comment]
lr太小，总bs是不是也很小？建议换大bs去训，不然增大epoch意义也不大，精度上限不高

**Comment by Hold-on-li** [comment]
> lr太小，总bs是不是也很小？建议换大bs去训，不然增大epoch意义也不大，精度上限不高

好的，谢谢啦
