### ISSUE TITLE
关于YoLoV5训练问题

### ISSUE THREAD

**Issue by Hold-on-li** [PaddlePaddle/PaddleYOLO#111]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问一下，YoloV5配置文件并没有像PaddleDetection中配置预训练模型参数的形式，YoloV5具体在哪配置预训练模型呢？

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/43    3. Fintune 
训练命令最后加`-o pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov5_s_300e_coco.pdparams`
配置文件里加一行`pretrain_weights: xxx`就行，参照 https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/configs/ppyoloe/ppyoloe_plus_crn_l_80e_coco.yml#L13

**Comment by Hold-on-li** [comment]
> #43 3. Fintune 训练命令最后加`-o pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov5_s_300e_coco.pdparams` 配置文件里加一行`pretrain_weights: xxx`就行，参照 https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/configs/ppyoloe/ppyoloe_plus_crn_l_80e_coco.yml#L13

好的，谢谢
