### ISSUE TITLE
"暂未支持完全训练" 是什么意思？

### ISSUE THREAD

**Issue by tino926** [PaddlePaddle/PaddleYOLO#116]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在许多模型的说明页面中，会有这样一句"暂未支持完全训练"。
请问这是什么意思呢？是指训练出来的精度会不如原始版本吗？

**Comment by nemonameless** [comment]
这样注明的几个模型，都先不要去训练。yolov6-3.0 和 yolov8的训练是放在飞桨黑客松论文复现赛，别的没时间排期复现 或 优先级不高。

就当前性能来看，PPYOLOE+ 模型在只训80epoch的情况下基本上还是略胜市面上的其他竞品模型，你可以训更多epoch试试。

此外PPYOLOE+的小目标、旋转框、密集检测、半监督检测、检测蒸馏、tiny版本、obj365预训练、transformer等超大型backbone、各种人车工业垂类应用都很齐全，欢迎使用。
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe
https://github.com/PaddlePaddle/PaddleDetection/releases/tag/v2.6.0
