### ISSUE TITLE
如何遍历优化器的不同参数组

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleYOLO#118]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

torch的优化器中可以加入不同的参数分组并进行遍历，如下所示：
![image](https://user-images.githubusercontent.com/71805205/229432227-346b4b32-0e94-49cb-80cc-eebae089203c.png)
![image](https://user-images.githubusercontent.com/71805205/229432283-82c07664-9496-4887-adcd-e35bfa7875c9.png)
我想问下，paddle中如何遍历优化器的不同参数分组

**Comment by nemonameless** [comment]
增加 param_groups 参数，可以同时clone PaddleDetection和Paddle的代码对照着 搜和看。Paddle源码，搜group看看， https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/optimizer/optimizer.py
