### ISSUE TITLE
Failed, NCCL error /paddle/paddle/fluid/distributed/collective/NCCLTools.h:227 'unhandled cuda error'

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/PaddleYOLO#121]
### 问题描述 Please describe your issue

(paddle) ubuntu@ubuntu:~/data1/paddle/PaddleYOLO$ sh train.sh 
LAUNCH INFO 2023-04-06 22:26:19,689 -----------  Configuration  ----------------------
LAUNCH INFO 2023-04-06 22:26:19,689 devices: 0,1,2,3
LAUNCH INFO 2023-04-06 22:26:19,689 elastic_level: -1
LAUNCH INFO 2023-04-06 22:26:19,689 elastic_timeout: 30
LAUNCH INFO 2023-04-06 22:26:19,689 gloo_port: 6767
LAUNCH INFO 2023-04-06 22:26:19,689 host: None
LAUNCH INFO 2023-04-06 22:26:19,689 ips: None
LAUNCH INFO 2023-04-06 22:26:19,689 job_id: default
LAUNCH INFO 2023-04-06 22:26:19,689 legacy: False
LAUNCH INFO 2023-04-06 22:26:19,689 log_dir: log
LAUNCH INFO 2023-04-06 22:26:19,689 log_level: INFO
LAUNCH INFO 2023-04-06 22:26:19,689 master: None
LAUNCH INFO 2023-04-06 22:26:19,689 max_restart: 3
LAUNCH INFO 2023-04-06 22:26:19,689 nnodes: 1
LAUNCH INFO 2023-04-06 22:26:19,689 nproc_per_node: None
LAUNCH INFO 2023-04-06 22:26:19,689 rank: -1
LAUNCH INFO 2023-04-06 22:26:19,689 run_mode: collective
LAUNCH INFO 2023-04-06 22:26:19,689 server_num: None
LAUNCH INFO 2023-04-06 22:26:19,689 servers: 
LAUNCH INFO 2023-04-06 22:26:19,689 start_port: 6070
LAUNCH INFO 2023-04-06 22:26:19,689 trainer_num: None
LAUNCH INFO 2023-04-06 22:26:19,689 trainers: 
LAUNCH INFO 2023-04-06 22:26:19,689 training_script: tools/train.py
LAUNCH INFO 2023-04-06 22:26:19,689 training_script_args: ['-c', 'configs/custom/yolov7_l_300e_garbroom.yml', '--use_vdl=true', '--vdl_log_dir=vdl_dir/scalar', '-o', 'use_gpu=true', '--amp', '--eval', '-o', 'pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov7_l_300e_coco.pdparams']
LAUNCH INFO 2023-04-06 22:26:19,689 with_gloo: 1
LAUNCH INFO 2023-04-06 22:26:19,689 --------------------------------------------------
LAUNCH INFO 2023-04-06 22:26:19,690 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-04-06 22:26:19,696 Run Pod: wqaevk, replicas 4, status ready
LAUNCH INFO 2023-04-06 22:26:19,749 Watching Pod: wqaevk, replicas 4, status running
I0406 22:26:20.925828 62343 tcp_utils.cc:181] The server starts to listen on IP_ANY:55485
I0406 22:26:20.926013 62343 tcp_utils.cc:130] Successfully connected to 127.0.1.1:55485
Failed, NCCL error /paddle/paddle/fluid/distributed/collective/NCCLTools.h:227 'unhandled cuda error'
LAUNCH INFO 2023-04-06 22:26:22,754 Pod failed
LAUNCH ERROR 2023-04-06 22:26:22,754 Container failed !!!
Container rank 0 status failed cmd ['/home/ubuntu/anaconda3/envs/paddle/bin/python', '-u', 'tools/train.py', '-c', 'configs/custom/yolov7_l_300e_garbroom.yml', '--use_vdl=true', '--vdl_log_dir=vdl_dir/scalar', '-o', 'use_gpu=true', '--amp', '--eval', '-o', 'pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov7_l_300e_coco.pdparams'] code 1 log log/workerlog.0 
env {'LESSOPEN': '| /usr/bin/lesspipe %s', 'CONDA_PROMPT_MODIFIER': '(paddle) ', 'LANGUAGE': 'zh_CN:en', 'USER': 'ubuntu', 'LC_TIME': 'zh_CN.UTF-8', 'LIBVA_DRIVERS_PATH': '/opt/intel/mediasdk/lib64', 'SSH_AGENT_PID': '8591', 'XDG_SESSION_TYPE': 'x11', 'SHLVL': '1', 'LD_LIBRARY_PATH': '/usr/local/cuda-11.6/lib64::/home/ubuntu/TensorRT-8.4.2.4/lib:/usr/include/nccl.h', 'QT4_IM_MODULE': 'fcitx', 'HOME': '/home/ubuntu', 'CONDA_SHLVL': '2', 'DESKTOP_SESSION': 'ubuntu', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'GTK_MODULES': 'gail:atk-bridge', 'LC_MONETARY': 'zh_CN.UTF-8', 'MANAGERPID': '8412', 'DBUS_STARTER_BUS_TYPE': 'session', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus,guid=f59584064ecf2b3bbf046a7f642e0871', 'COLORTERM': 'truecolor', '_CE_M': '', 'IM_CONFIG_PHASE': '1', 'GTK_IM_MODULE': 'fcitx', 'LOGNAME': 'ubuntu', 'JOURNAL_STREAM': '8:113415', '_': '/usr/bin/sh', 'PKG_CONFIG_PATH': ':/usr/local/lib/pkgconfig', 'XDG_SESSION_CLASS': 'user', 'USERNAME': 'ubuntu', 'TERM': 'xterm-256color', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', '_CE_CONDA': '', 'WINDOWPATH': '2', 'PATH': '/home/ubuntu/anaconda3/envs/paddle/bin:/home/ubuntu/anaconda3/condabin:/usr/local/cuda-11.6/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'SESSION_MANAGER': 'local/ubuntu:@/tmp/.ICE-unix/8714,unix/ubuntu:/tmp/.ICE-unix/8714', 'INVOCATION_ID': '7660e1261ca64774b019405ac9777ffd', 'PAPERSIZE': 'a4', 'XDG_MENU_PREFIX': 'gnome-', 'LC_ADDRESS': 'zh_CN.UTF-8', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/6935613b_781b_4b1f_b950_f6d5fd6cc9e4', 'XDG_RUNTIME_DIR': '/run/user/1000', 'DISPLAY': ':1', 'LANG': 'zh_CN.UTF-8', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'CONDA_PREFIX_1': '/home/ubuntu/anaconda3', 'XMODIFIERS': '@im=fcitx', 'LIBVA_DRIVER_NAME': 'iHD', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'GNOME_TERMINAL_SERVICE': ':1.97', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'CONDA_PYTHON_EXE': '/home/ubuntu/anaconda3/bin/python', 'SHELL': '/bin/bash', 'LC_NAME': 'zh_CN.UTF-8', 'QT_ACCESSIBILITY': '1', 'GDMSESSION': 'ubuntu', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'CONDA_DEFAULT_ENV': 'paddle', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', 'QT_IM_MODULE': 'fcitx', 'PWD': '/home/ubuntu/data1/paddle/PaddleYOLO', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'CONDA_EXE': '/home/ubuntu/anaconda3/bin/conda', 'CLUTTER_IM_MODULE': 'fcitx', 'DBUS_STARTER_ADDRESS': 'unix:path=/run/user/1000/bus,guid=f59584064ecf2b3bbf046a7f642e0871', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'LC_NUMERIC': 'zh_CN.UTF-8', 'CONDA_PREFIX': '/home/ubuntu/anaconda3/envs/paddle', 'LC_PAPER': 'zh_CN.UTF-8', 'VTE_VERSION': '6003', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/home/ubuntu/anaconda3/envs/paddle/lib/python3.8/site-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/home/ubuntu/anaconda3/envs/paddle/lib/python3.8/site-packages/cv2/qt/fonts', 'POD_NAME': 'wqaevk', 'PADDLE_MASTER': '127.0.1.1:55485', 'PADDLE_GLOBAL_SIZE': '4', 'PADDLE_LOCAL_SIZE': '4', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:55486,127.0.1.1:55487,127.0.1.1:55488,127.0.1.1:55489', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:55486', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '4', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2023-04-06 22:26:22,754 ------------------------- ERROR LOG DETAIL -------------------------
I0406 22:26:20.925828 62343 tcp_utils.cc:181] The server starts to listen on IP_ANY:55485
I0406 22:26:20.926013 62343 tcp_utils.cc:130] Successfully connected to 127.0.1.1:55485
Failed, NCCL error /paddle/paddle/fluid/distributed/collective/NCCLTools.h:227 'unhandled cuda error'
LAUNCH INFO 2023-04-06 22:26:22,955 Exit code 1

**Comment by nemonameless** [comment]
请先确认下paddle-gpu是否安装成功

**Comment by jia0511** [comment]
成功了啊，我单独训练没问题，多卡训练报NCCL问题，NCCL我用Yolov5框架多卡训练没问题

**Comment by lvcaiwen** [comment]
使用的卡是不是3090

**Comment by jia0511** [comment]
@lvcaiwen 是的

**Comment by nemonameless** [comment]
请尽量安装最新版本paddle，如2.4.2以上，且注意cuda gcc等版本对应

**Comment by jia0511** [comment]
我就是参考你们官方，装了2.4.2.post116
![微信图片_20230531161237](https://github.com/PaddlePaddle/PaddleYOLO/assets/24822418/6569bf44-9728-46f6-883e-2d9ed4750d4a)

**Comment by jia0511** [comment]
来看看我配置哪里有问题？用你们代码单卡训没问题，多卡就不行
![2023-05-31 21-09-12屏幕截图](https://github.com/PaddlePaddle/PaddleYOLO/assets/24822418/8b9e8802-6e70-4548-94b3-1e25fe731cb9)
![2023-05-31 21-15-49屏幕截图](https://github.com/PaddlePaddle/PaddleYOLO/assets/24822418/69563210-9a07-4b54-96bc-7504a1a06dff)

**Comment by nemonameless** [comment]
gcc9.2有点太高了，可能没有适配的或适配的不好，常用的是gcc8.2的。可以换个环境或降低版本，如果继续使用此版本，得问下 https://github.com/PaddlePaddle/Paddle/issues

**Comment by jia0511** [comment]
虽然还没尝试，但是认为回答了我们的问题，所以关闭
