### ISSUE TITLE
%run tools/infer.py 报错：TypeError: 'numpy.float32' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by overman1** [PaddlePaddle/PaddleYOLO#129]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

model_name='yolov8' 
job_name='yolov8_x_500e_coco' 

config=f'configs/{model_name}/{job_name}.yml'
weights=f'../pretrain/{job_name}.pdparams'

%run tools/infer.py -c {config} -o weights={weights} use_gpu=false --infer_img=demo/000000014439_640x640.jpg --draw_threshold=0.5
<img width="1086" alt="1" src="https://user-images.githubusercontent.com/56420014/233585026-946d6898-a675-44b8-8522-ae75268c19ab.png">
<img width="1089" alt="2" src="https://user-images.githubusercontent.com/56420014/233585101-f0ddf0d4-a99f-451d-8f98-e9426d378415.png">

### 复现环境 Environment

OS：macOS-13.1-x86_64-i386-64bit
paddlepaddle：2.4.1
Paddleyolo :2.6
Python 3.10.9 
NO GPU

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
自测没有问题。建议使用最新代码，且手打一行完整运行命令再试下：
`python tools/infer.py -c configs/yolov8/yolov8_x_500e_coco.yml -o use_gpu=false weights=yolov8_x_500e_coco.pdparams --infer_img=demo/000000329219.jpg`
