### ISSUE TITLE
yolov5p6在coco上的预训练权重

### ISSUE THREAD

**Issue by FrankerSun** [PaddlePaddle/PaddleYOLO#13]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问有yolov5p6在coco上的pretrain_weights吗？

**Comment by nemonameless** [comment]
暂时没有，是想做预训练去训业务数据集吗？可以试下yolov7的几个p6权重，精度本身也高的多
