### ISSUE TITLE
FLOPs不一致

### ISSUE THREAD

**Issue by GaoShanwen** [PaddlePaddle/PaddleYOLO#130]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，按照提示将params和flops设置为True，计算的flops和params比工程给出的略小，是设置的有问题还是paddle有哪里进行了优化呢？

| mode | Params | FLOPs |
| -- | -- | -- |
| PPYOLOE+ -s (given) | [7.93](https://github.com/PaddlePaddle/PaddleYOLO/blob/5436cb4fed03ac6b22da6565ff2520111b1f3ea4/docs/MODEL_ZOO_en.md#pp-yoloe) | 17.36|
| PPYOLOE+ -s (run code) | 7.61 | 16.16(doubled) |
| YOLOv5 -n (given) | [1.87](https://github.com/PaddlePaddle/PaddleYOLO/blob/5436cb4fed03ac6b22da6565ff2520111b1f3ea4/docs/MODEL_ZOO_en.md#yolov5) | 4.52 |
| YOLOv5 -n (run code) | 1.76 | 4.18(doubled) |

**Comment by nemonameless** [comment]
FLOPs和paddleslim版本有关。Params一般误差不大

**Comment by GaoShanwen** [comment]
那工程所给出FLOPs对应的是那个paddleslim版本呢，我当前用的是2.1.0

**Comment by nemonameless** [comment]
请使用devleop版本paddleslim
