### ISSUE TITLE
关于PaddleYOLOv8和官方YOLOv8在RK3588上的部署问题

### ISSUE THREAD

**Issue by 7288Fzq** [PaddlePaddle/PaddleYOLO#133]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

开发者们好！我想问一下PaddleYOLOv8和官方YOLOv8是否都支持在Fast Deploy中转换为RKNN模型以用于在RK3588平台上进行部署。YOLOv8的pose模型现在支持转换了吗。

**Comment by nemonameless** [comment]
本仓库是模型套件，是模型的训练验证infer。各种部署相关的请向 https://github.com/PaddlePaddle/FastDeploy/issues 提问吧。
pose还未支持。
