### ISSUE TITLE
参考本仓库configs/yolov8的readme，无法导出模型

### ISSUE THREAD

**Issue by Yi-sir** [PaddlePaddle/PaddleYOLO#137]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

参考yolov8 readme中的命令【python tools/export_model.py -c configs/yolov8/yolov8_s_500e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/yolov8_s_500e_coco.pdparams】  尝试导出模型。
报错信息：
```shell
Traceback (most recent call last):
  File "tools/export_model.py", line 110, in <module>
    main()
  File "tools/export_model.py", line 106, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 64, in run
    trainer = Trainer(cfg, mode='test')
  File "/root/projects/PaddleYOLO/ppdet/engine/trainer.py", line 96, in __init__
    self.model.yolo_head._initialize_biases()  # Note: must added
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 1144, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'YOLOv8Head' object has no attribute '_initialize_biases'
```

### 复现环境 Environment

- OS: ubuntu18.04
- PaddleYOLO version: release/2.6
- PaddleDetection version: release/2.6
- paddlepaddle: 2.4.1
- python: 3.7.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
已修复
