### ISSUE TITLE
请问 YOLO5模型中的anchor大小 有程序可以根据我自己标注的数据集进行计算吗？

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleYOLO#14]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/77281977/187108124-6aca9fe6-bfde-4706-8a14-fc004d98816c.png)

**Comment by nemonameless** [comment]
和yolov3、ppyolov1 v2一样可以通过anchor聚类获得。但是默认anchor设置是在COCO大规模数据上聚类得到的，鲁棒性很高，图片较少时不建议重新聚类设置了，或者除非极端宽高比的数据集可能要设置下。


参考 [docs/tutorials/data/PrepareDetDataSet.md](https://github.com/nemonameless/PaddleDetection_YOLOSeries/blob/develop/docs/tutorials/data/PrepareDetDataSet.md#%E5%8F%AF%E9%80%89%E7%94%9F%E6%88%90anchor)

### (可选)生成Anchor
在yolo系列模型中，大多数情况下使用默认的anchor设置即可, 你也可以运行`tools/anchor_cluster.py`来得到适用于你的数据集Anchor，使用方法如下：
``` bash
python tools/anchor_cluster.py -c configs/ppyolo/ppyolo.yml -n 9 -s 608 -m v2 -i 1000
```
目前`tools/anchor_cluster.py`支持的主要参数配置如下表所示：

|    参数    |    用途    |    默认值    |    备注    |
|:------:|:------:|:------:|:------:|
| -c/--config | 模型的配置文件 | 无默认值 | 必须指定 |
| -n/--n | 聚类的簇数 | 9 | Anchor的数目 |
| -s/--size | 图片的输入尺寸 | None | 若指定，则使用指定的尺寸，如果不指定, 则尝试从配置文件中读取图片尺寸 |
|  -m/--method  |  使用的Anchor聚类方法  |  v2  |  目前只支持yolov2的聚类算法  |
|  -i/--iters  |  kmeans聚类算法的迭代次数  |  1000  | kmeans算法收敛或者达到迭代次数后终止 |
