### ISSUE TITLE
C++部署的问题

### ISSUE THREAD

**Issue by gutao0315** [PaddlePaddle/PaddleYOLO#15]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我把训练出来的模型转成inference 在paddleDetection release2.3里的depoly CPP里部署 没有用
训练出来的inference模型是不是得在这个版本的CPP里部署才行

**Comment by nemonameless** [comment]
这个代码库的版本介于 release/2.4和develop之间，近期会拉取最新develop分支合并。CPP部署差别不大，建议用新点的分支。

**Comment by gutao0315** [comment]
那如果我現在要用 哪個版本的cpp是能直接用的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 下午3:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nemonameless/PaddleDetection_YOLOSeries] C++部署的问题 (Issue #15)





 
这个代码库的版本介于 release/2.4和develop之间，近期会拉取最新develop分支合并。CPP部署差别不大，建议用新点的分支。

**Comment by nemonameless** [comment]
现在这个代码库的就行
