### ISSUE TITLE
yolov8训练自己的数据集

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleYOLO#151]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在训练自己的数据集的过程中进行了eval 给出的数据是这样的 精度为0是为什么呢
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/25cdff3a-d2d6-4eae-8331-7238270e1ca4)

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/43 
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/13104100/6f3ad5f3-175b-41c9-b8c9-151bb7ead6af)


你好，请发下更多详细信息，包括配置文件并说明改动，以及此epoch的训练log，包括loss，可截图

**Comment by iyangiii** [comment]
好的 我没有用预训练权重 
训练日志如下：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/32b41d81-9deb-4caf-a797-784a7e60b353)
之前保留的vdl图片如下：
![62d4118ede36c36405466621d2ae5e8](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/179f4649-52eb-46ee-9462-7ebb3e1d6c27)
配置文件如下：（对数据集的路径和epoch进行了修改，因为我的数据集较小）
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/090037ba-04b1-4317-9354-59fcc75e1fad)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/36bac786-f009-41b2-938e-ecfc9dff610d)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/24053076-8130-4295-84d7-346f8e0b4519)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/f66f2b42-fec3-48eb-a9d5-6f32e2f4dfb6)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/5ae2e345-1331-4b82-9089-9c2a068fb36c)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/f27ae48d-aed9-4cfc-8fb9-47498be28051)

**Comment by iyangiii** [comment]
> 

不好意思 配置文件图片发错了一张 
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/bc33b0cb-618b-4cbe-a834-9db2af49672a)

**Comment by nemonameless** [comment]
加载coco权重预训练去试试吧，应该主要是这个原因。如果裸训才10epoch精度未必高得再等更多epoch。且总bs尽量不要低于32，资源不够用建议换小模型或改小尺度。
此外如果你需要改epoch数，则optimizer_500e.yml和yolov8_reader.yml里，所有的500epoch都得改成你设置的80epoch，reader里的mosaic_epoch也得改成相应70epoch。

**Comment by iyangiiiii** [comment]
> 加载coco权重预训练去试试吧，应该主要是这个原因。如果裸训才10epoch精度未必高得再等更多epoch。且总bs尽量不要低于32，资源不够用建议换小模型或改小尺度。 此外如果你需要改epoch数，则optimizer_500e.yml和yolov8_reader.yml里，所有的500epoch都得改成你设置的80epoch，reader里的mosaic_epoch也得改成相应70epoch。

好的好的 我试试看

**Comment by iyangiiiii** [comment]
> 加载coco权重预训练去试试吧，应该主要是这个原因。如果裸训才10epoch精度未必高得再等更多epoch。且总bs尽量不要低于32，资源不够用建议换小模型或改小尺度。 此外如果你需要改epoch数，则optimizer_500e.yml和yolov8_reader.yml里，所有的500epoch都得改成你设置的80epoch，reader里的mosaic_epoch也得改成相应70epoch。

这里的预训练模型都是ppyoloe的 需要改成yolo8吗

**Comment by iyangiiiii** [comment]
> 加载coco权重预训练去试试吧，应该主要是这个原因。如果裸训才10epoch精度未必高得再等更多epoch。且总bs尽量不要低于32，资源不够用建议换小模型或改小尺度。 此外如果你需要改epoch数，则optimizer_500e.yml和yolov8_reader.yml里，所有的500epoch都得改成你设置的80epoch，reader里的mosaic_epoch也得改成相应70epoch。

出现这样的日志是有问题吗
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/9f1dd47f-d4d4-4315-af20-123fef8e5cf4)

**Comment by iyangiii** [comment]
> 加载coco权重预训练去试试吧，应该主要是这个原因。如果裸训才10epoch精度未必高得再等更多epoch。且总bs尽量不要低于32，资源不够用建议换小模型或改小尺度。 此外如果你需要改epoch数，则optimizer_500e.yml和yolov8_reader.yml里，所有的500epoch都得改成你设置的80epoch，reader里的mosaic_epoch也得改成相应70epoch。

已经按你说的操作了 bs也增大到了32 但是还是为0 加载过coco权重预训练了
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/610cc254-506a-4624-80f7-29aad36475f4)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/101607550/764a8fdc-bf2b-406c-b55c-0f99abd3c2ca)

**Comment by LDX17** [comment]
@iyangiiiii 你好，请问你用的什么版本的paddle？我看你也是用的aistudio训练的yolov8，没有报错。我用过paddle2.4.1和2.5.0，都报错，无法训练。

**Comment by thanhhuyenpt** [comment]
@iyangiiiii I had the same problem, did you solve it?

**Comment by nemonameless** [comment]
从log图片看第二个epoch loss反而上升了，是不合理的，可能是数据集太小了，或者可以减小lr再试试。
