### ISSUE TITLE
关于Yolov5s 的qat量化问题。我使用配置qat的方式进行训练是正常的，但是验证和推理时都有问题。

### ISSUE THREAD

**Issue by sg-goldrush** [PaddlePaddle/PaddleYOLO#153]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在YOLOv5s上，我使用官方配置的文档训练roadsign_voc数据集，能正常训练 验证 和推理。

但是我想将 YOLOv5s 进行QAT量化。我也是使用配置文件 configs/slim/quant/yolov5_s_qat.yml

配置如下：

pretrain_weights: output/yolov5_s_75e_roadsign_voc/best_model
slim: QAT
QAT:
  quant_config: {
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear']}
  print_model: True
epoch: 20

基本上就是正常配置，量化卷积和激活。在训练的时候，还会正常显示精度，但是在我用 eval.py的时候验证有问题，在infer.py的时候，推理图片也会出错。

请问我要如何量化yolov5s 这个模型呢？（用ptq量化后的精度也是直接都没了）

**Comment by nemonameless** [comment]
请前往https://github.com/PaddlePaddle/Paddleslim 提问吧

**Comment by sg-goldrush** [comment]
好的
