### ISSUE TITLE
YOLOV8训练报错

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleYOLO#154]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

YOLOV8训练报错如图，请问是啥原因？
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/c858f231-7f97-4388-97f0-7eb63c027c5d)
paddle版本：paddle develop
paddleyolo 2.6

**Comment by nemonameless** [comment]
可以试下2.4.2版本的paddle。代码改动情况也请说明下以便排查谢谢。

**Comment by sdreamforchen** [comment]
V8的训练速度还没有RT-DETR快。这是以为ELAN架构的原因吗
都是基于paddle进行训练的

**Comment by LorenzoSun-V** [comment]
@LDX17 你好，我也遇到了相同问题，请问大佬是怎么解决的？
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/13c206b0-0d64-4e2d-a119-5a09a88c0aaa)
看报错信息的话，dataset已经加载成功，但是在Dataloader取数据的时候报错了。
我把worker_num设置为0，可以正常训练，但是loss太大就卡住了：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/7f293eb2-b5fb-4e80-be2d-d86917e4d875)
这个问题我在训练yolov7u的时候也遇到了。

**Comment by LDX17** [comment]
@LorenzoSun-V https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov8/_base_/yolov8_cspdarknet.yml#L2 注释掉就没报错了
