### ISSUE TITLE
NotImplementedError: ProgramTranslator hasn't implemented multiple decorators. Please remove staticmethod in forward

### ISSUE THREAD

**Issue by STNPSG** [PaddlePaddle/PaddleYOLO#158]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

def forward(self, x):
            return self.act(self.bn(self.conv(x)))
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

NotImplementedError: ProgramTranslator hasn't implemented multiple decorators. Please remove staticmethod in forward

**Comment by nemonameless** [comment]
报错请按末班提问，说明下如何运行和复现这个问题的谢谢。https://github.com/PaddlePaddle/PaddleYOLO/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&projects=&template=1_bug-report.yml
同时确认下环境版本正确无误，paddle请安装使用2.4.2以上。
