### ISSUE TITLE
Aistudio  paddlepaddle2.5.0训练yolov8报错

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/PaddleYOLO#165]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Aistudio  paddlepaddle2.5.0训练yolov8报错如下：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/7010c020-6319-448e-9c87-22327f72dc36)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/3ff1b5e7-67fd-4782-8534-3fcb8562fc52)
环境：Aistudio  paddlepaddle2.5.0   paddleyolo2.6
代码改动：
1）yolov8_s_500e_coco-my.yml文件
_BASE_: [
  '../datasets/kitticoco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_500e.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

save_dir: /home/aistudio/output
print_flops: true
print_params: true
log_iter: 50
snapshot_epoch: 10
weights: /home/aistudio/output/yolov8_s_500e_coco-my/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov8_s_500e_coco.pdparams

epoch: 200

LearningRate:
  base_lr: 0.00125
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 200
    min_lr_ratio: 0.01
  - !ExpWarmup
    epochs: 1

TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128

mosaic_epoch: &mosaic_epoch 190 # last 10 epochs close mosaic, totally 500 epochs as default

2）kitticoco_detection.yml文件
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/23f4ce40-631f-491e-aba6-c71f7ca3756d)

运行命令：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/055d5705-b551-47ea-8b20-3f6ecd393d3b)

**Comment by nemonameless** [comment]
0iter打印出log信息了吗？建议再自查下数据集制作。也可同数据集去训yolov3或ppyoloe看看是否会有同样问题。
换用paddle2.4.2版本，就没有0D Tensor那些警告信息。

**Comment by LDX17** [comment]
0iter没有打印出log信息。同数据集去训yolov3或ppyoloe正常。aistudio没有对应的paddle2.4.2版本。请问如何去排除这些错误？

**Comment by nemonameless** [comment]
关闭mosaic或syncbn试试。 https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov8/_base_/yolov8_cspdarknet.yml#L2  注释或者
```
mosaic_epoch: &mosaic_epoch -1

- MosaicPerspective: {mosaic_prob: 0.0, target_size: *input_size}
```

最新PaddleYOLO代码已经修复0D Tensor那些警告信息，paddle版本都可正常训了。

**Comment by LDX17** [comment]
能训练了，但是训了10epoch的结果如下：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/4b31349c-7b3c-4051-8be9-5b544f3c20e0)
我加了COCO预训练权重的
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/66930694/7e862b42-7ed4-4db7-a7a7-c8421d15398c)

**Comment by nemonameless** [comment]
你好，加载预训练权重后去训，建议可以每两三个epoch就看下精度。谢谢。
