### ISSUE TITLE
训练yolo出现'Tensor.numpy()[0]' to 'float(Tensor)' 异常打印

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/PaddleYOLO#168]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

报错如下：
I0723 22:47:29.653092 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0723 22:47:29.653215 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0723 22:47:30.037526 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0723 22:47:30.037608 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0723 22:47:30.422574 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I0723 22:47:30.422659 43348 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.

我的conda环境：
------------------- ------------- --------------------------------------------------
aiohttp             3.8.4
aiosignal           1.3.1
anyio               3.6.2
astor               0.8.1
async-timeout       4.0.2
attrs               23.1.0
Babel               2.12.1
bce-python-sdk      0.8.83
bcrypt              4.0.1
blinker             1.6.2
Brotli              1.0.9
certifi             2023.5.7
cffi                1.15.1
charset-normalizer  3.1.0
click               8.1.3
coloredlogs         15.0.1
contourpy           1.0.7
cryptography        40.0.2
cycler              0.11.0
Cython              0.29.34
decorator           5.1.1
fastapi             0.95.1
ffmpy               0.3.0
Flask               2.3.2
flask-babel         3.1.0
flatbuffers         23.3.3
fonttools           4.39.4
frozenlist          1.3.3
fsspec              2023.5.0
future              0.18.3
gevent              22.10.2
geventhttpclient    2.0.2
gradio              3.11.0
greenlet            2.0.2
grpcio              1.54.0
h11                 0.12.0
httpcore            0.15.0
httpx               0.24.0
humanfriendly       10.0
idna                3.4
importlib-metadata  6.6.0
importlib-resources 5.12.0
itsdangerous        2.1.2
Jinja2              3.1.2
kiwisolver          1.4.4
linkify-it-py       2.0.2
markdown-it-py      2.2.0
MarkupSafe          2.1.2
matplotlib          3.7.1
mdit-py-plugins     0.3.5
mdurl               0.1.2
mpmath              1.2.1
multidict           6.0.4
numpy               1.24.4
onnx                1.14.0
onnxruntime         1.14.1
opencv-python       4.7.0.72
opt-einsum          3.3.0
orjson              3.8.12
packaging           23.1
paddle-bfloat       0.1.7
paddle2onnx         1.0.6
paddlepaddle-gpu    2.5.0.post116
pandas              2.0.1
paramiko            3.1.0
Pillow              9.5.0
pip                 23.2.1
protobuf            3.20.3
psutil              5.9.5
pycocotools         2.0.6
pycparser           2.21
pycryptodome        3.17
pydantic            1.10.7
pydub               0.25.1
PyNaCl              1.5.0
pyparsing           3.0.9
python-dateutil     2.8.2
python-multipart    0.0.6
python-rapidjson    1.10
pytz                2023.3
PyYAML              6.0
rarfile             4.0
requests            2.30.0
scipy               1.10.1
setuptools          67.8.0
shapely             2.0.1
six                 1.16.0
sniffio             1.3.0
starlette           0.26.1
sympy               1.11.1
tensorrt            8.4.2.4
terminaltables      3.1.10
tqdm                4.65.0
tritonclient        2.33.0
typeguard           3.0.2
typing_extensions   4.5.0
tzdata              2023.3
uc-micro-py         1.0.2
urllib3             2.0.2
uvicorn             0.22.0
visualdl            2.5.2
websockets          11.0.3
Werkzeug            2.3.4
wheel               0.38.4
x2paddle            1.4.1
yarl                1.9.2
yolox               0.3.0         /home/ubuntu/lingpu/TensorRT-For-YOLO-Series/YOLOX
zipp                3.15.0
zope.event          4.6
zope.interface      6.0
我的cuda环境：

cuda11.6 cudnn8.6  python3.8

**Comment by nemonameless** [comment]
代码拉到最新的了吗？已经修复过一次，参照 https://github.com/PaddlePaddle/PaddleYOLO/commit/292467d9704f4f31f7209a4ae53b36b080336a57

**Comment by jia0511** [comment]
拉倒最新版本修复了
