### ISSUE TITLE
YOLOv6怎么将网络融合

### ISSUE THREAD

**Issue by Ywenjun123** [PaddlePaddle/PaddleYOLO#171]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我用convert_to_deploy()融合RepConv输出结果不对

**Comment by nemonameless** [comment]
导出模型的时候自动会融合的
https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.6/configs/yolov6#4%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B

**Comment by Ywenjun123** [comment]
> 导出模型的时候自动会融合的 https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.6/configs/yolov6#4%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B
我就是想用他的主干网络

**Comment by Ywenjun123** [comment]
> 导出模型的时候自动会融合的 https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.6/configs/yolov6#4%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B
我就是想用他的主干网络，但是执行这个后输出结果差的很大
def model_switch(model):
        ''' Model switch to deploy status '''
        for layer in model.sublayers():
            if hasattr(layer, 'convert_to_deploy'):
                    layer.convert_to_deploy()

**Comment by nemonameless** [comment]
你好，可以直接使用导出后的权重。
