### ISSUE TITLE
YOLOv5能否加入实例分割分支

### ISSUE THREAD

**Issue by DreamMaker777** [PaddlePaddle/PaddleYOLO#172]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

官方YOLOv5支持实例分割分支，请问paddle版本能否加入这一分支？https://github.com/ultralytics/yolov5
![Snipaste_2023-07-24_17-39-03](https://github.com/PaddlePaddle/PaddleYOLO/assets/31379701/f19aea5e-32ff-4007-a349-093da6d24357)

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
感谢关注，后续有时间会进行开发。

**Comment by nemonameless** [comment]
您好，develop分支已支持yolov5实例分割图推理，但是暂无计划继续支持训练了，谢谢。
