### ISSUE TITLE
yolov6不支持训练吗

### ISSUE THREAD

**Issue by WainBK** [PaddlePaddle/PaddleYOLO#173]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

yolov6不支持训练吗

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/yolov6_v20  暂时有一个2.0的训练。
yolov6最新的3.0 4.0是放在论文复现赛中，https://github.com/PaddlePaddle/PaddleYOLO/pull/146 ，但是选手复现的精度没有验收通过。我们内部后续有时间会开发。也感谢选手的付出和PR。

**Comment by WainBK** [comment]
meiyouzhegewenjian

**Comment by nemonameless** [comment]
你好，develop分支已支持训练。谢谢。
