### ISSUE TITLE
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

### ISSUE THREAD

**Issue by ZhangLe-fighting** [PaddlePaddle/PaddleYOLO#18]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 94, in __init__
    self.dataset, cfg.worker_num)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/data/reader.py", line 197, in __call__
    self.loader = iter(self.dataloader)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/reader.py", line 566, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 381, in __init__
    self._try_put_indices()
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 695, in _try_put_indices
    indices = next(self._sampler_iter)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/batch_sampler.py", line 262, in __iter__
    assert len(indices) == self.total_size
AssertionError
Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7fd205cfbbe0>>
Traceback (most recent call last):
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 712, in __del__
    self._try_shutdown_all()
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
INFO 2022-09-05 16:27:07,857 launch_utils.py:343] terminate all the procs

As a beginner, I can't solve this problem alone. Please help me. Thank you！

**Comment by ZhangLe-fighting** [comment]
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
babel                     2.10.3                   pypi_0    pypi
bce-python-sdk            0.8.74                   pypi_0    pypi
brotlipy                  0.7.0           py36h8f6f2f9_1001    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cffi                      1.14.6           py36hd8eec40_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.0.4                    pypi_0    pypi
cryptography              2.5              py36hb7f436b_1    conda-forge
cudatoolkit               11.2.2              hbe64b41_10    conda-forge
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flask                     2.0.3                    pypi_0    pypi
flask-babel               2.0.0                    pypi_0    pypi
freetype                  2.8.1                hfa320df_1    conda-forge
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                      py_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
lap                       0.4.0                    pypi_0    pypi
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_2    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.18.0               h780b84a_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
motmetrics                1.2.5                    pypi_0    pypi
numpy                     1.19.5           py36hfc0c790_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.0.2u               h516909a_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
paddle-bfloat             0.1.7                    pypi_0    pypi
paddledet                 2.4.0                    pypi_0    pypi
paddlepaddle-gpu          2.3.2           py36_gpu_cuda11.2_many_linux    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle
pandas                    1.1.5                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1                   pypi_0    pypi
protobuf                  3.18.0           py36hc4f0c31_0    conda-forge
pyclipper                 1.3.0.post3              pypi_0    pypi
pycocotools               2.0.4                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodome              3.15.0                   pypi_0    pypi
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 3.0.7                    pypi_0    pypi
pysocks                   1.7.1            py36h5fab9bb_3    conda-forge
python                    3.6.2                         0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.2.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  6.2                           2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                59.6.0                   pypi_0    pypi
shapely                   1.8.4                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.13.0                        0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.5.18                        0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tqdm                      4.64.0                   pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
visualdl                  2.4.0                    pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.29.0                   py36_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xmltodict                 0.13.0                   pypi_0    pypi
xz                        5.2.3                         0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11                        0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by ZhangLe-fighting** [comment]
![image](https://user-images.githubusercontent.com/55420158/188413440-61dca610-62e5-4519-b921-f0fd865c6e9a.png)

**Comment by nemonameless** [comment]
提问请遵循issue模板，说明下改动了什么，版本和环境是什么，以便排查问题。

**Comment by ZhangLe-fighting** [comment]
改动：只改了配置文件
coco_detection.yml 文件中 num_classes: 4
yolov7p6_elannet.yml 文件中 YOLOv7Head: anchors: [[29, 35], [41, 62], [79, 37], [96, 101], [185, 58], [155, 174], [298, 125], [267, 290], [621, 176], [414, 402], [880, 414], [945, 949]] （tools/anchor_cluster.py 生成）
yolov7p6_reader.yml 文件中 worker_num: 1 ； TrainReader:下batch_size: 4 ； EvalReader:下 batch_size: 4 

版本：
paddlepaddle-gpu   2.3.2
paddledet                 2.4.0
paddle-bfloat           0.1.7
python                     3.6.2
cudatoolkit              11.2.2  
cudnn                      8.1.0.77

服务器环境：
Tesla P40 服务器 Linux gpu 4.15.0-142-generic系统
Anaconda下使用conda创建的python3.6的虚拟环境，然后安装了paddle2.3.2 和paddledetection_yoloseries

**Comment by ZhangLe-fighting** [comment]
训练命令：export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m paddle.distributed.launch --log_dir=./yolo7_dygraph/ --gpus 4,5,6,7 tools/train.py -c configs/yolov7/yolov7p6_e6e_300e_coco.yml --eval -o use_gpu=true

将上述命令换成单卡训练会出现内存不足的错误，卡的内存占用会一直上升直到崩溃

**Comment by nemonameless** [comment]
一开始训就显存一直上升直到崩溃，就说明bs过大了，调小点就行。
训练命令加上`--amp`混合精度训练，加上可以同bs下减小显存占用。

**Comment by ZhangLe-fighting** [comment]
> 一开始训就显存一直上升直到崩溃，就说明bs过大了，调小点就行。 训练命令加上`--amp`混合精度训练，加上可以同bs下减小显存占用。

我使用四张卡，worker_num=1, bs=4 也会这样，单张卡显存22919MiB，报错为：
File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

这个报错是多卡训练的报错，应该没办法再减小bs了，加上混合精度训练依旧会出现上述问题

**Comment by nemonameless** [comment]
trainreader里的 bs=4 是指每卡的bs。但是再缩小的话总bs也过小了会影响精度。我也是paddle2.3.2，但是python3.7，没有出现这样的问题，要么升级下python试试。

**Comment by ZhangLe-fighting** [comment]
好的，感谢回答，我这边试一下。

**Comment by ZhangLe-fighting** [comment]
> trainreader里的 bs=4 是指每卡的bs。但是再缩小的话总bs也过小了会影响精度。我也是paddle2.3.2，但是python3.7，没有出现这样的问题，要么升级下python试试。

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 
python -m paddle.distributed.launch --log_dir=./ppyoloe_dygraph/ --gpus 2,3,4,7 tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --eval --amp

python升级到3.7（新建了个测试环境）依旧出现上述问题，我查看了报错的py文件，但是水平有限看不出哪里有问题，希望作者可以帮忙查看一下
我这里coco数据格式单卡训练和voc数据格式的多卡训练都没有出现这个问题，只有coco数据格式的多卡会报错

附上报错：
loading annotations into memory...
Done (t=0.25s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/hik/zhangle16/paddledet/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 97, in __init__
    self.dataset, cfg.worker_num)
  File "/home/hik/zhangle16/paddledet/PaddleDetection_YOLOSeries/ppdet/data/reader.py", line 197, in __call__
    self.loader = iter(self.dataloader)
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 566, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 381, in __init__
    self._try_put_indices()
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 695, in _try_put_indices
    indices = next(self._sampler_iter)
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/batch_sampler.py", line 262, in __iter__
    assert len(indices) == self.total_size
AssertionError


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1662449374 (unix time) try "date -d @1662449374" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x61d7) received by PID 25589 (TID 0x7efda056c700) from PID 25047 ***]

Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7efd344aec20>
Traceback (most recent call last):
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 712, in __del__
    self._try_shutdown_all()
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
INFO 2022-09-06 15:29:41,695 launch_utils.py:343] terminate all the procs

**Comment by nemonameless** [comment]
voc格式的多卡训练没有问题，而coco格式有问题吗？直接多卡训coco数据集也有问题吗？
[相关issue](https://github.com/PaddlePaddle/PaddleDetection/search?q=AttributeError%3A+%27_DataLoaderIterMultiProcess%27+object+has+no+attribute+%27_shutdown%27&type=issues)
rm -rf /dev/shm/* 清理一下再训下试试
其他可能的解决方法参考 https://github.com/PaddlePaddle/PaddleDetection/issues/3279 ,  https://github.com/PaddlePaddle/PaddleDetection/issues/2555

**Comment by ZhangLe-fighting** [comment]
AssertionError
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1662457696 (unix time) try "date -d @1662457696" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0xacff) received by PID 44993 (TID 0x7f45d0865700) from PID 44287 ***]

Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f45647a7c20>
Traceback (most recent call last):
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 712, in __del__
    self._try_shutdown_all()
  File "/home/hik/anaconda3/envs/paddledet_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

这是现在这个报错，然后单卡训练发现ap全为0

**Comment by nemonameless** [comment]
> voc格式的多卡训练没有问题，而coco格式有问题吗？直接多卡训coco数据集也有问题吗？ [相关issue](https://github.com/PaddlePaddle/PaddleDetection/search?q=AttributeError%3A+%27_DataLoaderIterMultiProcess%27+object+has+no+attribute+%27_shutdown%27&type=issues) rm -rf /dev/shm/* 清理一下再训下试试 其他可能的解决方法参考 [PaddlePaddle/PaddleDetection#3279](https://github.com/PaddlePaddle/PaddleDetection/issues/3279) , [PaddlePaddle/PaddleDetection#2555](https://github.com/PaddlePaddle/PaddleDetection/issues/2555)

这里提到的解决方法都试过了吗？还是报这个错？你的数据集有多大，总张数多少？
单卡eval AP为0可能是数据集gt制作有问题，可以可视化检查下或截图看下刚开始训和1epoch时的loss收敛情况。

**Comment by ZhangLe-fighting** [comment]
好的，我试下，数据集4000张，大概是1080p或2k的图，上面有的方法都试了，还是会报错。
单卡ap为0的时候训练超级快，不应该这么快的...
我查看一下问题，然后再给您反馈

**Comment by ZhangLe-fighting** [comment]
> > voc格式的多卡训练没有问题，而coco格式有问题吗？直接多卡训coco数据集也有问题吗？ [相关issue](https://github.com/PaddlePaddle/PaddleDetection/search?q=AttributeError%3A+%27_DataLoaderIterMultiProcess%27+object+has+no+attribute+%27_shutdown%27&type=issues) rm -rf /dev/shm/* 清理一下再训下试试 其他可能的解决方法参考 [PaddlePaddle/PaddleDetection#3279](https://github.com/PaddlePaddle/PaddleDetection/issues/3279) , [PaddlePaddle/PaddleDetection#2555](https://github.com/PaddlePaddle/PaddleDetection/issues/2555)
> 
> 这里提到的解决方法都试过了吗？还是报这个错？你的数据集有多大，总张数多少？ 单卡eval AP为0可能是数据集gt制作有问题，可以可视化检查下或截图看下刚开始训和1epoch时的loss收敛情况。

目前voc格式的多卡训练经过测试是没问题的，但是coco格式的多卡训练会报上面列举的错误，暂时未解决，coco格式的单卡训练，可能是数据集格式转换的问题，我这边刚入门排查较慢哈

**Comment by ZhangLe-fighting** [comment]
index created!
<class 'ppdet.modeling.architectures.yolo.YOLOv3'>
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 443, in train
    self._flops(flops_loader)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 933, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddleslim/core/dygraph.py", line 162, in dygraph2program
    original_outputs = layer(*inputs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolo.py", line 127, in get_pred
    return self._forward()
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolo.py", line 118, in _forward
    yolo_head_outs, self.inputs['scale_factor'])
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/heads/ppyoloe_head.py", line 370, in post_process
    pred_dist.transpose([0, 2, 1]))
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/bbox_utils.py", line 780, in batch_distance2bbox
    x1y1 = -lt + points
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 4116, 2] and the shape of Y = [8400, 2]. Received [4116] in X is not equal to [8400] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
INFO 2022-09-07 11:50:42,890 launch_utils.py:343] terminate all the procs
INFO 2022-09-07 11:50:42,890 launch_utils.py:343] terminate all the procs
ERROR 2022-09-07 11:50:42,890 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
ERROR 2022-09-07 11:50:42,890 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-09-07 11:50:46,895 launch_utils.py:343] terminate all the procs
INFO 2022-09-07 11:50:46,895 launch_utils.py:343] terminate all the procs
INFO 2022-09-07 11:50:46,895 launch.py:402] Local processes completed.
INFO 2022-09-07 11:50:46,895 launch.py:402] Local processes completed.

更改coco数据之后，单卡和多卡训练都会出现上述问题

**Comment by ZhangLe-fighting** [comment]
感谢开发者对我的问题进行解答，后面经过测试，voc和coco格式的数据均能正常训练。
初步排查的原因是：
1. 在yolov7p6_e6e_300e_coco.yml上不能训练的原因是硬件条件不行，会造成内存不足
2. 在ppyoloe_crn_l_300e_coco.yml上coco数据格式训练时，单卡ap为0和多卡各类报错的原因是coco数据集转换存在问题

再次感谢！

**Comment by nemonameless** [comment]
祝贺，主要还是你自己通过实践解决的。
