### ISSUE TITLE
你好，大佬，我下载了看您发布的v20好像没有yolov6lite 

### ISSUE THREAD

**Issue by WainBK** [PaddlePaddle/PaddleYOLO#180]
### 问题描述 Please describe your issue

RTMdet trainning not supported yet

**Comment by nemonameless** [comment]
yolov6在PaddleYOLO里的训练只支持到2.0，yolov6lite是yolov6官方4.0的时候发布的。PaddleYOLO 的develop分支支持yolov6lite推理预测，但是还不支持训练。PaddleYOLO 的yolov6_v20分支支持的yolov6训练是和yolov6官方2.0对齐的。
RTMdet不支持训练，只支持推理部署。由于短期内还有更高优的开发以及人力紧张，RTMdet和yolov6 4.0复现可能要暂缓一阵子。

**Comment by nemonameless** [comment]
您好，develop分支已支持yolov6lite，谢谢。
