### ISSUE TITLE
VOC2007数据集训练yoloV8 MAP值很低

### ISSUE THREAD

**Issue by RoderickSYSZ** [PaddlePaddle/PaddleYOLO#181]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在使用VOC2007数据集进行训练yoloV8时，发现最终mAP(0.50, 11point) = 7.76%。我的配置文件如下：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/24957256/0133b23a-1b6b-4667-9a81-4587f8d39165)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/24957256/fcce4ce2-6972-47c2-8d98-c0e434aeeeab)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/24957256/7541fc19-f839-44c0-a720-600b1867139a)
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/24957256/98fb2c1a-d8c2-410a-ad7f-2a09e901b21b)

**Comment by nemonameless** [comment]
训比coco数据集量级小很多的自定义数据集，需要加载coco权重做预训练，#43 
```
3. Fintune 微调训练：
除了更改数据集的路径外，训练一般推荐加载对应模型的COCO预训练权重去fintune，会更快收敛和达到更高精度，如：

# fintune with single GPU：
# CUDA_VISIBLE_DEVICES=0 python tools/train.py -c ${config} --eval --amp -o pretrain_weights=https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams

# fintune with multi GPU：
python -m paddle.distributed.launch --log_dir=./log_dir --gpus 0,1,2,3,4,5,6,7 tools/train.py -c ${config} --eval --amp -o pretrain_weights=https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_s_80e_coco.pdparams
```
