### ISSUE TITLE
文档链接失效

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/PaddleYOLO#183]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.自定义数据集的标注制作，请参考[DetAnnoTools](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/tutorials/data/DetAnnoTools.md);

2.自定义数据集的训练准备，请参考[PrepareDataSet](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/tutorials/PrepareDataSet.md)。
以上

https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/docs/MODEL_ZOO_cn.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.6/docs/tutorials/data
