### ISSUE TITLE
ins_seg分支可用吗

### ISSUE THREAD

**Issue by panp4n** [PaddlePaddle/PaddleYOLO#184]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

目前PaddleYOLO ins_seg分支可用吗？  我看配置中还没有预训练模型

**Comment by nemonameless** [comment]
暂不可用，后续有时间在再开发。

**Comment by nemonameless** [comment]
您好，develop分支支持yolo系列的几个模型的实例分割推理，但是暂无计划继续支持训练了，谢谢。
