### ISSUE TITLE
PaddleYOLOv8是否支持关键点检测

### ISSUE THREAD

**Issue by Zaughter** [PaddlePaddle/PaddleYOLO#189]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

能否用PaddleYOLOv8进行关键点检测类型的训练与部署

**Comment by nemonameless** [comment]
暂时还不支持，后续有时间再开发。

**Comment by nemonameless** [comment]
暂无计划支持了，谢谢。
您可以使用这些模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs/keypoint
