### ISSUE TITLE
YOLOv8在客制化数据集上训练出现SystemError

### ISSUE THREAD

**Issue by LorenzoSun-V** [PaddlePaddle/PaddleYOLO#191]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

我制作了一个客制化数据集，用labelimg标注后转成coco格式，其中有一些负样本没有标签，在coco标签中的表现为在images字段有image_id，但在annotations字段没有对应image_id的标签。在数据集中，我已设置allow_empty=True，并在yolov5和yolox上可以正常训练和推理。
但在yolov8训练时，会出现以下bug：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/18485ece-13b1-45e5-99c2-7c90400021cb)
看报错信息的话，dataset已经加载成功，但是在Dataloader取数据的时候报错了。
我把worker_num设置为0，可以正常训练，但是loss太大就卡住了：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/228000fc-84d4-42b9-bda7-bf349cebb26d)
这个问题我在训练yolov7u的时候也遇到了。

我的配置文件为：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/15952224-474d-45fd-b09d-0a89e6d22a24)
修改的`optimizer_100e.yml`为：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/42413198/61a980ae-bfad-4282-9daa-b70e18bc26b3)

### 复现环境 Environment

- OS: Linux
- PaddlePaddle-gpu: 2.5.1.post117
- PaddleDetection: 2.6.0
- Python: 3.7.14
- CUDA: 11.7
- GCC: 8.2.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by LorenzoSun-V** [comment]
另外我试了一下原始的coco配置文件训练，yolov8是可以正常训练的。

**Comment by LorenzoSun-V** [comment]
根据 [#164](https://github.com/PaddlePaddle/PaddleYOLO/issues/164) 的回答，把 use_shared_memory 设为False可以正常训练，但是同时也出现了训练loss一直为0的情况。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/166   谢谢建议，后续进展在166中更新
