### ISSUE TITLE
目标检测：忽略某些模糊的目标

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/PaddleYOLO#195]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问在使用PPYOLOE-SOD时，有办法将一些不确定类别的模糊的目标在标签中通过ignore标记成忽略样本，在训练时将这些目标物体忽略掉么？
如果有办法的话，该怎么操作呢？

**Comment by nemonameless** [comment]
数据集制作的时候，设定一个字段'ignore'就行。
可以自行搜索下coco格式的ignore

**Comment by Jorsen0** [comment]
> 数据集制作的时候，设定一个字段'ignore'就行。 可以自行搜索下coco格式的ignore

设置完之后呢，代码支持么，还是要配置一些东西？

**Comment by nemonameless** [comment]
设置完即可使用，或者您也可以自己做数据集的时候单独划一个背景类或者密集类作为ignore类加进去使用。主要是数据制作和配置上的操作。
