### ISSUE TITLE
yolov8训练好的模型如何在vc++生成的项目中调用？

### ISSUE THREAD

**Issue by zelohon** [PaddlePaddle/PaddleYOLO#196]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我使用官方yolov8 训练好的.pt文件  然后我想在PaddleYOLO 的vc++项目中使用  我应该怎么做？ PaddleYOLO 模型文件好像不支持PT和ONNX？ 我应该怎么办？

**Comment by nemonameless** [comment]
请参照 https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/detection/yolov8/cpp
导出onnx参照：
```
python3.7 tools/export_model.py  -c $config -o weights=yolov8_s_500e_coco.pdparams use_gpu=true

paddle2onnx --model_dir output_inference/yolov8_s_500e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file yolov8_s_500e_coco.onnx
```

**Comment by zelohon** [comment]
看了下 好像不行啊  好像得转换特定格式的模型才可以？

**Comment by nemonameless** [comment]
后续请前往请参照 [https://github.com/PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) 使用和提问吧
