### ISSUE TITLE
使用预训练的模型进行推理，有识别结果。基于预训练的模型训练Visdrone数据集后，使用训练后的模型进行推理，检测多张该数据集的图片，均无识别结果。

### ISSUE THREAD

**Issue by retioa11** [PaddlePaddle/PaddleYOLO#197]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

推理命令：
-c F:/PaddleYolo/PaddleYOLO-release-2.6/configs/yolov8/yolov8_n_500e_coco.yml -o weights=F:/PaddleYolo/PaddleYOLO-release-2.6/tools/output/yolov8_n_500e_coco/9.pdparams --infer_dir=F:/PaddleYolo/PaddleYOLO-release-2.6/demo
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/81463532/272e3612-40e3-4258-b8bd-de72ceb385cd)

训练命令：
-c F:/PaddleYolo/PaddleYOLO-release-2.6/configs/yolov8/yolov8_n_500e_coco.yml -o weights=E:/33EdgeAccelerate/Code/PretrainedModels/yolov8_n_500e_coco.pdparams

数据集的配置文件：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/81463532/ea3df33d-6b3e-42c1-ac46-2d5df3999329)

训练日志：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/81463532/6a23abc8-0878-43c9-883a-68b8dc38b1d1)

从Github下载代码后，只改了数据集的配置文件。怀疑是类别数目没有修改，但是没有找到解决问题的办法？ 刚接触PaddlePaddle，希望可以指点一下？ 如何训练自己的数据集，并可以正确进行推理？

**Comment by retioa11** [comment]
还修改了这个文件的第二行：
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/81463532/c592e547-b966-49bc-ae2a-66b6b8d9a863)

**Comment by nemonameless** [comment]
数据量太少不建议从头训，需要加载预训练权重。训练命令后加上 
`-o pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov8_n_500e_coco.pdparams`

**Comment by retioa11** [comment]
@nemonameless 训练命令中，已经加了 这个配置。不是这个原因。类别数除了在数据集的配置文件中修改，还需要修改别处吗？

**Comment by nemonameless** [comment]
先设置--draw_threshold=0.1看看能否画出框来，然后eval下是否mAP正常？如果均正常，则就是画图阈值太高的原因。如果不正常则是训的不好的原因。

**Comment by njflove** [comment]
> 数据量太少不建议从头训，需要加载预训练权重。训练命令后加上 `-o pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov8_n_500e_coco.pdparams`

从头训练预计起步多少数据量？
