### ISSUE TITLE
现在支持训练yolov8了吗？

### ISSUE THREAD

**Issue by rocketbear** [PaddlePaddle/PaddleYOLO#199]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有人能成功训练yolov8吗？

我尝试训练yolov8，感觉有问题。

配置文件yolov8_reader.yml里对训练集的transform是这样的：
    - Decode: {}
    - MosaicPerspective: {mosaic_prob: 1.0, target_size: *input_size}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}

通过代码可以看到，Decode输出的gt_bbox是xyxy格式，但MosaicPerspective里会先做xyhwn2xyxy，这样框就完全不对了。
使用Decode或把Decode换程yolov5的那种DecodeNormResize，训练结果loss都是爆炸飞起。

求成功经验。

**Comment by rocketbear** [comment]
估计短期内没人来回答，自己答了吧。

把Decode改成DecodeNormResize后，还是能训练的。
没跑大数据集，就拿yolov8_n，用coco val训练，coco val测试，直接拿训练好的yolov8_n_coco模型来初始化，跑了一百多个epoch，mAP已经超过0.3了。
因为数据集小，每个epoch只有一百个step左右，因此warm up要改多一点，我用了30个epoch做warm up。
尽管直接用训练好的模型初始化，刚开始的时候loss还是从三百跳到四百多才缓慢下降。要是仍然保持3个epoch warm up，loss直接爆炸到几万然后掉到0。
或者，下调学习率也许可以收到和增加warm up epoch数量类似的效果。

但无论如何，用Decode + MosaicPerspective肯定是错误的，Decode必须换成DecodeNormResize。

**Comment by nemonameless** [comment]
您好，现在代码确实有问题，感谢反馈，已经在排查训练验证中周末会更新完正确的。最初yolov8训练合入的时候验证过是ok的，后来相关代码有改动但是漏了验证yolov8，会尽快对代码库做全面排查，周末会更新完全。
此外yolov8训练周期较长，如果您需求紧急或想快速无误地训出高精度的结果，推荐也可以尝试使用PP-YOLOE+和RT-DETR，谢谢~

**Comment by nemonameless** [comment]
您好，develop分支先前已更新修复了。谢谢。
