### ISSUE TITLE
yolov7的FPN必须要3个branch

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleYOLO#20]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

yoloV7 tiny 
我想使用两个header进行预测，因为我的目标都是小目标，大小都很一致，所以我希望使用两个header即可，进行加速

但是配置文件修改后，无法训练

  File "/raid/zhangss/Tim.Zhang/002_PaddleKit/PaddleDetection_YOLOSeries/ppdet/modeling/necks/yolo_fpn.py", line 1150, in __init__
    self.in_channels[2], out_ch, 1, 1, act=act)  # 512->256

这里的2对fpn进行了限制，必须要有3个header

### 复现环境 Environment

-os ubuntu
-paddle 2.3

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
建议改输出只返回两层特征就行，要加速的话只返回特征图较小的两层，但我觉得可能效果不佳。
里面的fpn pan怎么连的最好不要改动，改动了大概率效果也不佳。
