### ISSUE TITLE
模型保存时报错

### ISSUE THREAD

**Issue by songh11** [PaddlePaddle/PaddleYOLO#208]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

问题描述：使用 export_model.py 保存模型时报错

```
python3 tools/export_model.py -c=configs/yolov5/yolov5_s_300e_coco.yml --output_dir=./inference_model -o weights=weights/yolov5_s_300e_coco.pdparams
```

报错信息：
```
  File "/home/songhan/sh_share_111/Paddle/PaddleYOLO-develop/ppdet/engine/trainer.py", line 1021, in _get_infer_cfg_and_input_spec
    self.model, input_spec=input_spec, full_graph=True)
TypeError: declarative() got an unexpected keyword argument 'full_graph'
```

### 复现环境 Environment

paddleyolo版本：develop
paddlepaddle版本：2.4.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
更新一下paddle，使用 2.5及以上版本试试

**Comment by songh11** [comment]
> 更新一下paddle，使用 2.5及以上版本试试

感谢回复，我这边需要在 python3.6 环境跑，只能用 2.5 以下版本，我把 full_graph 去掉可以保存，请问这样保存的模型会有问题么

**Comment by nemonameless** [comment]
没问题的，在您的环境能跑通就行。
