### ISSUE TITLE
infer.py: error: unrecognized arguments: --video_file =XXXXX 

### ISSUE THREAD

**Issue by SatanSu90** [PaddlePaddle/PaddleYOLO#21]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

infer.py直接检测视频提示参数不支持，infer_img不支持视频，直接检测视频参数是否变化

### 复现环境 Environment

docker
2.3.2
gpu
cuda11.2
cudnn8 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
infer_img是单张图片啊，`--video_file=xxx.mp4`就行。
建议仔细看参数说明https://github.com/nemonameless/PaddleDetection_YOLOSeries/blob/develop/deploy/python/utils.py#L41

**Comment by SatanSu90** [comment]
不行，提示infer.py: error: unrecognized arguments: --video_file=./demo/68210786d36b1a5affdef58ab7ad7ea1.mp4

**Comment by nemonameless** [comment]
请用现在默认分支代码再试试。
