### ISSUE TITLE
ppyoloe_seg的实例分割模型下载链接失效了

### ISSUE THREAD

**Issue by xgyyao** [PaddlePaddle/PaddleYOLO#210]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe_seg的实例分割模型下载链接失效了，https://paddledet.bj.bcebos.com/models/ppyoloe_seg_m_80e_coco.pdparams，是否可以重新提供下可用的模型下载链接

**Comment by nemonameless** [comment]
你好，这个权重mask精度较低，我们近期会重训一个，再放到develop和release/2.7分支里公开。

**Comment by nemonameless** [comment]
暂时没有训了。之前有个临时权重可以试试，https://bj.bcebos.com/v1/paddledet/models/legacy_model/yolo_seg/ppyoloe_plus_ins_crn_m_80e.pdparams
