### ISSUE TITLE
关于检测和分割的多任务

### ISSUE THREAD

**Issue by TimZhang001** [PaddlePaddle/PaddleYOLO#215]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）;
 
我这边的场景除了检测外，还需要进行分类，是否可以考虑采用Mult-Task的方案，在输出检测结果的同时，也输出分割的结果？

2. 需求场景（请描述你的项目中为什么需要用此功能）; 

需要被检测物体的精确Mask信息

3. 功能描述（请简单描述或设计这个功能）

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/ins_seg/configs 可以搜_seg后缀的，支持实例分割推理，暂时未训练对齐。
