### ISSUE TITLE
有计划整合YOLOv9吗？

### ISSUE THREAD

**Issue by Ruanlt** [PaddlePaddle/PaddleYOLO#216]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有计划整合YOLOv9吗？有的话预计什么时候呢？

**Comment by nemonameless** [comment]
您好，暂时人力不足，低优开发，不确定什么时候能上。可以尝试PPYOLOE+和RT-DETR，应该可以满足绝大部分需求。

**Comment by Ruanlt** [comment]
了解了，感谢回复
