### ISSUE TITLE
如何查看参数量

### ISSUE THREAD

**Issue by ilovefanjian** [PaddlePaddle/PaddleYOLO#220]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

redetr中查看参数量的代码有误，paddle.flops下面参数名不对

**Comment by nemonameless** [comment]
configs/runtime.yml  下设置 print_flops: True 即可，https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/configs/runtime.yml#L8
RTDETR相关，可以在这里提问：https://github.com/PaddlePaddle/PaddleDetection/issues   or  https://github.com/lyuwenyu/RT-DETR/issues
