### ISSUE TITLE
yolov5_s_60e_voc.yml与yolov5_s_300e_coco.yml

### ISSUE THREAD

**Issue by Hari-Seldonn** [PaddlePaddle/PaddleYOLO#221]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.用configs\voc\yolov5_s_60e_voc.yml.和configs\yolov5\yolov5_s_300e_coco.yml训练VOC自定义数据集有多大的精度或者其他方面的差距
2.或者说yolov5_s_300e_coco.yml和yolov5_s_60e_voc.yml有什么区别（除了训练不同格式的训练集外），我看着好像没有多大区别。3.能用里面所有的XXXXXX_XXXX.coco.yml的模型来训练我的自定义的VOC训练集吗。（我试着也能训练）

**Comment by nemonameless** [comment]
1. yolov5_s_60e_voc.yml 和 yolov5_s_300e_coco.yml 看取名是epoch数不同，具体配置里看，前者里有写 pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov5_s_300e_coco.pdparams  意思是拿coco训300epoch后的权重做预训练，再去训voc，这样更快收敛，精度也更高
2. 区别除了数据集格式配置，就是训练epoch数和pretrain_weights的区别， yolov5_s_60e_voc.yml 里开头 _BASE_ 里有写继承自yolov5_s_300e_coco.yml。
3. 换数据集就是 config里开头的 _BASE_ 里的'../datasets/coco.yml',换成'../datasets/voc.yml'，可以自己定义
