### ISSUE TITLE
与测时未能显示标签

### ISSUE THREAD

**Issue by lbsonggz** [PaddlePaddle/PaddleYOLO#234]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在Conda虚拟环境中搭建PaddlePaddle，同时安装PaddleDetection和PaddleYOLO环境,并安装了requirements依赖项。运行python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000570688.jpg  测试时，PaddleDetection可显示标签，PaddleYOLO无法显示标签。
![Uploading 000000570688.jpg…]()
![Uploading 000000570688.jpg…]()
也设计了VOC格式的淡水鱼识别系统，采用YOLOX网络。运行infer时，也是无法显示标签，
![Uploading 2_pangxie.jpg…]()
![Uploading 3_jiyu.jpg…]()
查找各类资料也未发现具体原因。

**Comment by nemonameless** [comment]
![abaaec8bae71e35e43b701bf07a8120c](https://github.com/PaddlePaddle/PaddleYOLO/assets/13104100/56852b9b-b1a8-4547-8bdf-bfb2a3d61c8c)
无法显示标签是什么意思，是指图片里能检出框但框上没有种类名和score吗？测过develop分支是没这个问题的，可视化框的代码，两个库没有区别。建议再自查下环境版本问题等因素。

**Comment by lbsonggz** [comment]
是的，就是这个意思。与PaddleDetection相同的安装方法，也确实在develop分支，很奇怪。
![4_lingyu](https://github.com/PaddlePaddle/PaddleYOLO/assets/66626676/796d5239-4fe6-4f4d-8fcd-5c93f64860c4)
PaddleDetection就能显示种类名和score
![4_lingyu](https://github.com/PaddlePaddle/PaddleYOLO/assets/66626676/424d24e5-519f-4433-a4ca-715353b9c3c4)

**Comment by nemonameless** [comment]
没有复现您说的这个问题，建议先用PaddleDetection吧
