### ISSUE TITLE
关于昇腾910b部署和batchsize问题

### ISSUE THREAD

**Issue by IceHowe** [PaddlePaddle/PaddleYOLO#239]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

有两个问题：
1. （YOLO检测模型建议总batch_size至少大于64去训练，如果资源不够请换小模型或减小模型的输入尺度，为了保障较高检测精度，尽量不要尝试单卡训和总batch_size小于64训。）这个是仅对于YOLOv5-v8那些吗？还是包含了PP-YOLOE和E+？YOLOv8的话单卡精度高吗？
2. （新增昇腾910B硬件支持，支持的模型见 [模型列表](https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/docs/hardware/supported_models.md)）列表里只看到了PP-YOLOE seg，那么910b支持PP-YOLOE和PP-YOLOE+吗？还是说这两个都不支持？

**Comment by nemonameless** [comment]
1.针对所有yolo模型。单卡训只要bs开到64以上还是可以的，单卡总bs=8这种设置去训是训不高的。
2.PPYOLOE系列都支持，seg是指检测基础上的实例分割，模型上看就是新增了做seg的head。

**Comment by IceHowe** [comment]
> 1.针对所有yolo模型。单卡训只要bs开到64以上还是可以的，单卡总bs=8这种设置去训是训不高的。 2.PPYOLOE系列都支持，seg是指检测基础上的实例分割，模型上看就是新增了做seg的head。

1.这个情况对于PP-YOLOE系列及PP-YOLOE+也是这样必须单卡bs64以上吗？
2.PPYOLOE+也属于PPYOLOE系列是吗？是不是也可以支持昇腾910b？

谢谢

**Comment by nemonameless** [comment]
1.是的
2.是的
