### ISSUE TITLE
YOLO系列的剪枝提上日程了吗

### ISSUE THREAD

**Issue by sdreamforchen** [PaddlePaddle/PaddleYOLO#24]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

您好，我看YOLO系列的量化已经做好了。YOLO系列的剪枝会有更新吗？还是我们自己利用现有paddle的剪枝模型操作即可

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yghstill** [comment]
@sdreamforchen 建议你参考ppdet中结构化剪枝的demo尝试下：https://github.com/nemonameless/PaddleDetection_YOLOSeries/tree/develop/configs/slim/prune
