### ISSUE TITLE
为什么这个库的license要选择GPL呢？

### ISSUE THREAD

**Issue by nicken** [PaddlePaddle/PaddleYOLO#242]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

为什么这个库的license要选择GPL呢？而不是保持其他paddle库的apache-2.0?

**Comment by nemonameless** [comment]
您好，因为其中的yolov5-yolov10模型的原仓库都是GPL协议。
