### ISSUE TITLE
可以转成TinyYolo2_model吗

### ISSUE THREAD

**Issue by wangjunjx8868** [PaddlePaddle/PaddleYOLO#31]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

可以转成TinyYolo2_model吗

**Comment by nemonameless** [comment]
请再详细点描述你的需求谢谢。
可以自己尝试[一键运行全流程](https://github.com/nemonameless/PaddleDetection_YOLOSeries#%E4%B8%80%E9%94%AE%E8%BF%90%E8%A1%8C%E5%85%A8%E6%B5%81%E7%A8%8B)

**Comment by wangjunjx8868** [comment]
> 请再详细点描述你的需求谢谢。 可以自己尝试[一键运行全流程](https://github.com/nemonameless/PaddleDetection_YOLOSeries#%E4%B8%80%E9%94%AE%E8%BF%90%E8%A1%8C%E5%85%A8%E6%B5%81%E7%A8%8B)

我看百度的训练模型可以转onnx，但是onnx也分对很多类吧，微软的ML.NET 有个ObjectDetection，需要用到TinyYolo2_model.onnx文件，这个 Tiny Yolo2 很特殊?有指定的转换吗？

**Comment by nemonameless** [comment]
Yolov2太古老了，此代码库没有支持。建议使用更新的YOLO模型。
