### ISSUE TITLE
请问怎么单独实现一个优化器呢

### ISSUE THREAD

**Issue by diaoa1900** [PaddlePaddle/PaddleYOLO#32]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我想在自己的代码中使用yolov5的优化器，
我这样实现好像不对（base_lr还是0.1），请问该怎么实现呢？
![image](https://user-images.githubusercontent.com/65444591/191886130-75913a36-1f13-4642-a244-bff4fd46c337.png)

**Comment by nemonameless** [comment]
请参考  https://github.com/PaddlePaddle/models/blob/release/2.3/docs/lwfx/ArticleReproduction_CV.md#3.5

和 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Overview_cn.html#about-optimizer

**Comment by diaoa1900** [comment]
谢谢，但从这两处文档只能实现Momentum部分，YOLOv5LRDecay和ExpWarmup以及优化器的regularizer部分的实现并没有思路

**Comment by nemonameless** [comment]
你好，请参考这个：https://github.com/PaddlePaddle/PaddleYOLO/blob/develop/ppdet/optimizer/optimizer.py#L157
