### ISSUE TITLE
OSError: (External) CUDA error(719)

### ISSUE THREAD

**Issue by mr-abccc** [PaddlePaddle/PaddleYOLO#34]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

代码改动
![image](https://user-images.githubusercontent.com/35223774/192406664-a8d1da4d-3fa9-4072-9ded-042826d4172f.png)
![image](https://user-images.githubusercontent.com/35223774/192406690-33013fa3-4632-4fee-9020-99d102bcf6f0.png)
![image](https://user-images.githubusercontent.com/35223774/192406712-ea1b5e6a-c25b-41da-9eaf-64565bb85bcc.png)

shell
(ppyolo) D:\Code\_Paddle\PaddleYOLO>python tools/train.py -c configs/yolov7/yolov7_l_300e_coco.yml --eval
W0927 08:44:37.201936 15152 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.6
W0927 08:44:37.207935 15152 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Params:  Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [37.20547867])
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [7] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [7] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [7] and greater than or equal to 0, but received [0]
...............................................................................................................................................................................................................................................................
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [7] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [7] and greater than or equal to 0, but received [0]
Traceback (most recent call last):
  File "D:\Code\_Paddle\PaddleYOLO\tools\train.py", line 172, in <module>
    main()
  File "D:\Code\_Paddle\PaddleYOLO\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File "D:\Code\_Paddle\PaddleYOLO\tools\train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\engine\trainer.py", line 535, in train
    outputs = model(data)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 91, in get_loss
    return self._forward()
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 81, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\heads\yolo_head.py", line 755, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\losses\yolo_loss.py", line 512, in forward
    bs, as_, gjs, gis, targets, anchors = self.build_targets(
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\losses\yolo_loss.py", line 593, in build_targets
    indices, anch = self.find_3_positive(p, targets, anchors)
  File "D:\Code\_Paddle\PaddleYOLO\ppdet\modeling\losses\yolo_loss.py", line 784, in find_3_positive
    j = np.stack([np.ones_like(j), j, k, l, m])
  File "<__array_function__ internals>", line 180, in ones_like
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\numpy\core\numeric.py", line 280, in ones_like
    res = empty_like(a, dtype=dtype, order=order, subok=subok, shape=shape)
  File "<__array_function__ internals>", line 180, in empty_like
  File "C:\ProgramData\Anaconda3\envs\ppyolo\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 692, in __array__
    array = self.numpy()
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)

### 复现环境 Environment

Windows 10

python 3.9
paddlepaddle-gpu   2.3.2.post116
paddledet          2.4.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
win上请安装官网最新develop版本的paddle，版本号是0.0.0
单卡运行总bs只有2实在过小了不建议训，原版总bs是8x32=256。如果要训建议训tiny，并注意加载coco权重预训练，参照[doc](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/docs/MODEL_ZOO_cn.md#fintune%E8%AE%AD%E7%BB%83)

**Comment by mr-abccc** [comment]
![image](https://user-images.githubusercontent.com/35223774/192531203-95d1ff72-643b-4bb0-bf2b-2ff409329762.png)
![image](https://user-images.githubusercontent.com/35223774/192531228-35618cfc-de43-48af-bb52-0ccc106e6bc7.png)
更改版本之后，问题依旧。

**Comment by mr-abccc** [comment]
是没解决方案了，是么

**Comment by nemonameless** [comment]
不推荐win训，开发的时候没有win机器调试。

**Comment by nemonameless** [comment]
YOLO的检测建议bs至少大于32去训

**Comment by Plusmile** [comment]
您好，后续有解决这个问题吗？

**Comment by nemonameless** [comment]
请安装最新develop版本的paddle，别的环境如numpy等版本也请都升级下，建议最好使用linux平台

**Comment by Zhw1997** [comment]
> 请安装最新develop版本的paddle，别的环境如numpy等版本也请都升级下，建议最好使用linux平台

我在AIStudio里训yolov8也会报: OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:267).....这是为什么呢

**Comment by Zhw1997** [comment]
> 请安装最新develop版本的paddle，别的环境如numpy等版本也请都升级下，建议最好使用linux平台

我在AIStudio里训yolov8也会报: OSError: (External) CUDA error(719), unspecified launch failure.
[Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:267).....由于是自制数据集coco_detction类别设置为了1，但我数据集是但类别类别id是8，所以我改成10之后就可以训了，但目前来看效果好像一般...

**Comment by Zhw1997** [comment]
> 请安装最新develop版本的paddle，别的环境如numpy等版本也请都升级下，建议最好使用linux平台

我在AIStudio里训yolov8也会报: OSError: (External) CUDA error(719), unspecified launch failure.
[Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ../paddle/phi/backends/gpu/cuda/cuda_info.cc:267).....由于是自制数据集coco_detction类别设置为了1，但我数据集是单类别类别id是8，所以我改成10之后就可以训了，但目前来看效果好像一般...
