### ISSUE TITLE
关于 v7 隐性知识

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleYOLO#36]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我在用 paddle 实现 v7 加了隐性知识（use_implicit），特别是 ImplicitM obj loss 会炸掉，请问你们也遇到类似情况吗？

**Comment by nemonameless** [comment]
是的暂时不加训的，待完善。

**Comment by FL77N** [comment]
> 是的暂时不加训的，待完善。

其实 mean 设置为 1，更好，肯定是不会炸的，yolor 的论文也是这样设置的。官方代码我跑了，最终 ImplicitM 也是往 1 附近学习的

**Comment by nemonameless** [comment]
ok会尝试的

**Comment by FL77N** [comment]
> ok会尝试的

你好，我看 ppyolo 中 l 的 aug 里面有设置的 paste_in，但实际上 train 的时候是没用的是吗

**Comment by nemonameless** [comment]
https://github.com/WongKinYiu/yolov7/issues/855 
fix ImplicitM
paste_in暂时没加，影响应该不大，MosaicPerspective待重构和提速。
