### ISSUE TITLE
关于 v6 300 epoch

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleYOLO#41]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问关于 v6 s 等小模型的 300 epoch 后面会训吗

**Comment by nemonameless** [comment]
会训练的。

**Comment by FL77N** [comment]
> 会训练的。

其实我还有一个疑问，就是 v6 官方实现的 loss 最后会乘以 gpu 数量，paddle 这边不用进行这个操作嘛

**Comment by nemonameless** [comment]
已修复，漏写了是必须要乘num_gpus的。
