### ISSUE TITLE
是否支持win系统 voc数据集训练？

### ISSUE THREAD

**Issue by Gaoang112** [PaddlePaddle/PaddleYOLO#47]
在win系统下自定义 voc数据集训练，总是内存溢出，将bs调到1依然不行！
![image](https://user-images.githubusercontent.com/59632939/197832033-4c9a9c8d-8f9f-4186-aad0-95c103cc43aa.png)

**Comment by nemonameless** [comment]
支持的。请先参考 https://github.com/PaddlePaddle/PaddleYOLO/issues/43 ，voc数据集也一样。
训练命令后加--amp 开启混合精度训练可以降低显存占用，建议训yolov7_tiny模型，否则bs过小检测精度会极低，原版yolov7总bs是8x32=256。
