### ISSUE TITLE
输出onnx模型问题

### ISSUE THREAD

**Issue by Superyanzhuang** [PaddlePaddle/PaddleYOLO#48]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练YOLOX再导出模型时候按照教程关闭NMS，
![image](https://user-images.githubusercontent.com/88640736/198279075-851c5b0d-d9c0-4a86-b996-d9590f046c51.png)
但输出的onnx任然包含NMS
![image](https://user-images.githubusercontent.com/88640736/198278522-d5f04761-ddce-403c-a4cf-aa5f7974aef7.png)
请问如何解决？

**Comment by nemonameless** [comment]
你的导出命令是？有没有加 exclude_nms=True ？

**Comment by Superyanzhuang** [comment]
导出格式如下：

**Comment by Superyanzhuang** [comment]
![image](https://user-images.githubusercontent.com/88640736/198420798-963a00f8-a96b-4be7-8c1d-e719830fdcb3.png)
这个我导出格式

**Comment by Superyanzhuang** [comment]
感谢，已经成功导出非NMS的模型
