### ISSUE TITLE
项目能开一个develop分支么？

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleYOLO#49]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

对于单个版本分支作为main没啥毛病，后续每个分支都是一个release,对于本地git clone后某个版本，更新代码其实很麻烦。希望能改进

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/develop 
谢谢建议，先基于release/2.5切了个develop分支。之前是考虑需要和 PaddleDetection 的develop分支保持一致，目前那边develop分支改动较多，且要安装develop的paddle版本才可使用。这几天会同步。

**Comment by BeyondYourself** [comment]
> https://github.com/PaddlePaddle/PaddleYOLO/tree/develop 谢谢建议，先基于release/2.5切了个develop分支。之前是考虑需要和 PaddleDetection 的develop分支保持一致，目前那边develop分支改动较多，且要安装develop的paddle版本才可使用。这几天会同步。

赞
