### ISSUE TITLE
混淆矩阵，F1-score，P-R过程图等

### ISSUE THREAD

**Issue by Ss-shuang123** [PaddlePaddle/PaddleYOLO#50]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

像官方yolov5、yolov7一样，训练结束时，能够生成混淆矩阵、P-R图、F1-score过程图等
方便训练自己数据集时，后续进行优化与调整

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
谢谢，很好的建议，我们后面会排期安排。
