### ISSUE TITLE
yolov7训练

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleYOLO#51]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

config：yolov7p6_e6e_300e_coco.yml

![image](https://user-images.githubusercontent.com/28383188/200794147-81c8fa5e-d4e5-460c-8a70-8173f698ceb7.png)

![image](https://user-images.githubusercontent.com/28383188/200794283-22ab588e-e1f0-4c08-aaa7-d5e9a093cd5d.png)

很奇怪怎么没有这个网络层尼，导致训练不了模型

**Comment by nemonameless** [comment]
谢谢反馈，已修复，可以git pull更新下，迁移代码遗漏导致。
如果没有很大的显存资源，不建议直接训这么大的模型，可以训小点的模型。
