### ISSUE TITLE
yolov6 开启了dfl后 map为0

### ISSUE THREAD

**Issue by Yamabukiss** [PaddlePaddle/PaddleYOLO#52]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

```
_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov6_cspbep.yml',
  '_base_/yolov6_reader_fintune.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 20
snapshot_epoch: 10
pretrain_weights: /home/zq/segmentation/PaddleYOLO/output/iter1_L2_old_mosaic/yolov6_l_silu_300e_coco/best_model.pdparams
weights: 


act: 'silu'
training_mode: "conv_silu" # Note: L use silu


CSPBepBackbone:
  csp_e: 0.50

CSPRepPAN:
  csp_e: 0.50

EffiDeHead:
  reg_max: 16
  use_dfl: True
  iou_type: 'giou'
  loss_weight: {cls: 1.0, iou: 2.5, dfl: 0.5, cwd: 10.0}
  distill_weight: {cls: 2.0, dfl: 1.0} # 2:1 in L-relu version, will not work default (self_distill=False)


# Step 1: Training the base model, get 51.0+ mAP
TrainReader:
  batch_size: 16 # total batch_size = 32 * gpu_num

EvalReader:
  batch_size: 8


# Step 2: Self-distillation training, get 52.0+ mAP
# Please cancel the following comment and train again
#
#self_distill: False
#pretrain_weights: /home/zq/segmentation/PaddleYOLO/output/iter1_L2_old_mosaic/yolov6_l_silu_300e_coco/best_model.pdparams
#save_dir: output_distill
#weights:

#TrainReader:
#   batch_size: 16
#
```
以上为配置文件 开启了自蒸馏后一样是map为0

**Comment by nemonameless** [comment]
报错请按模板提问，自定义数据集请先阅读完文档，和数据集确保无误后再使用。https://github.com/PaddlePaddle/PaddleYOLO/issues/43

pretrain_weights 一般是填imagenet预训练或coco权重预训练，先检查下是不是写错了，还是本意就是要让你写的这个权重做预训练呢？
yolov6你的数据集下本身训的怎么样？没训好就不要开启自蒸馏去训了，自蒸馏训很久也增益不高的又浪费资源时间。
训练loss自己关注下是否异常，可以补充下loss的log信息便于排查问题。

最后建议直接训ppyoloe+，训业务数据集提点最大的就是加数据和超强预训练，加载obj365预训练训的又快又高。参照 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe/application

**Comment by Yamabukiss** [comment]
> 报错请按模板提问，自定义数据集请先阅读完文档，和数据集确保无误后再使用。#43
> 
> pretrain_weights 一般是填imagenet预训练或coco权重预训练，先检查下是不是写错了，还是本意就是要让你写的这个权重做预训练呢？ yolov6你的数据集下本身训的怎么样？没训好就不要开启自蒸馏去训了，自蒸馏训很久也增益不高的又浪费资源时间。 训练loss自己关注下是否异常，可以补充下loss的log信息便于排查问题。
> 
> 最后建议直接训ppyoloe+，训业务数据集提点最大的就是加数据和超强预训练，加载obj365预训练训的又快又高。参照 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe/application

我这里是在没有dfl开启得情况下 是能达到正常预期的  开启dfl训练过程中的loss下降也是正常的 就仅是在验证集上ap为0
