### ISSUE TITLE
yolov5版本提问

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/PaddleYOLO#53]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

配置文件在PaddleYOLO/configs/yolov5/yolov5_s_300e_coco.yml
请问，yolov5_s_300e_coco对应yolov5的pytorch中的6.2版本吗？因为在自己数据集上做实验需要与pytorch做一个对比；需要版本一致。非常感谢。

**Comment by nemonameless** [comment]
6.1版本。自己的数据集调参很重要，baseline很多参数也不一样，paddle版本需要较大bs才有优势，各版本间差距也小，认准一个使用就行了。
