### ISSUE TITLE
单卡训练

### ISSUE THREAD

**Issue by wexin-c** [PaddlePaddle/PaddleYOLO#54]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

单卡怎么训练呢？
已经在官网查询过[教程文档]，但是没有找到解答，都是默认8卡训练；
![image](https://user-images.githubusercontent.com/78461277/202187391-d8b14c88-9c57-465a-9316-48e1eeb9aca0.png)
3090单卡默认配置训练，训不动

**Comment by nemonameless** [comment]
```
CUDA_VISIBLE_DEVICES=0 python tools/train.py -c ${config} --eval
```
https://github.com/PaddlePaddle/PaddleYOLO#%E6%95%99%E7%A8%8B 文档请仔细阅读。
报bug请按模板提问谢谢。
https://github.com/PaddlePaddle/PaddleYOLO/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml

**Comment by wexin-c** [comment]
谢谢 我调小了bactchsize
