### ISSUE TITLE
同一张图片有较低概率（0.2%）出现不同的结果

### ISSUE THREAD

**Issue by xmxxiong** [PaddlePaddle/PaddleYOLO#56]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

用自己的数据集训练的模型，模型转换后，出现了预测同一张图片得到不同的结果：
结果1：[0, 0.95495987, 0.8209882, 980.28625, 908.0034, 1480.1486]

结果2：[0, 0.97286224, 101.02287, 0.46325487, 1358.9056, 696.56476]

### 复现环境 Environment

OS：linux
paddlepaddle-gpu:2.3.2
cuda:11.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
你好，请问是哪个模型？预测命令是什么？

**Comment by xmxxiong** [comment]
用的模型是：ppyoloe_plus_crn_x_80e_coco，预测: 先将模型用tools/export_model.py转换后， 使用deploy/python/infer.py脚本预测。请问是否在预测过程中的随机种子固定了嘛？是否需要额外再固定随机种子？

**Comment by xmxxiong** [comment]
detector.predict_image(
    img_list,
    FLAGS.run_benchmark,
    repeats=100,
    visual=FLAGS.save_images,
    save_results=FLAGS.save_results)

请问这里的  repeats=100,请问这里的repeats参数的作用是什么呢？

**Comment by xmxxiong** [comment]
经过几次测试，把repeats设为1可以解决该问题，同一张图片结果不一样的现象没有了

**Comment by nemonameless** [comment]
repeats 只在测速时使用，是否开启了`run_benchmark=True`？默认是不开的

**Comment by xmxxiong** [comment]
我看了代码，代码中run_benchmark=False,之前应该是我理解错了，和repeats应该没啥关系，后面我又进行了测试，问题又出现了，而且两个结果差距还比较大：
输出错误结果：img size:(716, 1552, 3) det:[0, 0.95453084, 24.728344, 752.5917, 588.38184, 1057.2423]
输出正确结果：img size:(716, 1552, 3) det:[0, 0.96529996, 149.76654, 66.880066, 1390.2249, 702.36096]
输出错误结果的box坐标已经超出图片尺寸范围了，

**Comment by xmxxiong** [comment]
我看了代码，代码中run_benchmark=False,之前应该是我理解错了，和repeats应该没啥关系，后面我又进行了测试，问题又出现了，而且两个结果差距还比较大：
输出错误结果：img size:(716, 1552, 3) det:[0, 0.95453084, 24.728344, 752.5917, 588.38184, 1057.2423]
输出正确结果：img size:(716, 1552, 3) det:[0, 0.96529996, 149.76654, 66.880066, 1390.2249, 702.36096]
输出错误结果的box坐标已经超出图片尺寸范围了，

**Comment by nemonameless** [comment]
你的图片只有一个目标吗？确定这两个框画的是同一个目标吗？你可以可视化出来看看
另外有较低概率（0.2%）是怎么算出来的？

**Comment by xmxxiong** [comment]
图片里只有一个目标，我这边可视化出来看过，正确的结果是正确的，错误的结果由于输出框的尺寸不对，无法可视化。0.2%的结果是我通过压力测试工具跑出来的

**Comment by xmxxiong** [comment]
测试结果显示，出现这种情况的图片样本不是固定的，而是随机的

**Comment by nemonameless** [comment]
你好，这个不影响使用。
