### ISSUE TITLE
 yolov5模型导出

### ISSUE THREAD

**Issue by wexin-c** [PaddlePaddle/PaddleYOLO#57]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Export

### Bug描述 Describe the Bug

模型训练完后使用导出命令行代码：
python tools/export_model.py -c configs/yolov5/yolov5_x_300e_coco.yml  -o weights=output/yolov5_x_300e_coco/best_model.pdparams TestReader.inputs_def.image_shape=[3,640,640] --output_dir=./inference_model
![image](https://user-images.githubusercontent.com/78461277/202607755-a41d457c-45cd-49ee-98e6-03041dda5bc6.png)
![image](https://user-images.githubusercontent.com/78461277/202607830-55629408-42c0-4f40-bbf7-8cf008a3462a.png)
![image](https://user-images.githubusercontent.com/78461277/202607861-90121ad6-15d5-48cc-a1a1-c7e8c0e4f8b0.png)
![image](https://user-images.githubusercontent.com/78461277/202607890-03f32716-f1df-4169-8032-29f0c2325499.png)
![image](https://user-images.githubusercontent.com/78461277/202607919-b21dd417-03b9-4fb2-9022-b9b2ac5e3248.png)

### 复现环境 Environment

-OS: Windows10
-PaddlePaddle: develop
-PaddleYOLO: PaddleYOLO-release-2.5
-Python: 3.8.0
-CUDA: 11.1
CUDNN: 8.0.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
代码有改动什么吗？刚git clone下来自测是没问题的。

**Comment by wexin-c** [comment]
> 

代码没有改动，有没有可能是我模型权重的问题？我使用的是自己的训练集训练的模型权重

**Comment by wexin-c** [comment]
> 

代码没有改动，有没有可能是我模型权重的问题？我使用的是自己的训练集训练的模型权重

**Comment by wexin-c** [comment]
> > 
> 
> 代码没有改动，有没有可能是我模型权重的问题？我使用的是自己的训练集训练的模型权重


> 代码有改动什么吗？刚git clone下来自测是没问题的。
模型训练时，只更改了batch_size和学习率，其他参数没有更改

**Comment by wexin-c** [comment]
> 代码有改动什么吗？刚git clone下来自测是没问题的。
您好，我用了官方的权总自测还是有问题

**Comment by nemonameless** [comment]
cuda11.0机器，最新develop 版本的paddle，自测没问题。请再仔细确认下是否拉取了最新代码，以及代码是否做了更改。

**Comment by wexin-c** [comment]
![image](https://user-images.githubusercontent.com/78461277/202827236-fd0b7ad6-f629-4bc3-b636-3ce7b19e9b9f.png)
![image](https://user-images.githubusercontent.com/78461277/202827252-6b1ed7e9-d1f8-4bf9-85c9-9f01731acc97.png)
cuda11.1机器，最新develop 版本的paddle，PaddleYOLO2.5版本，使用官方的权重yolov5_x_300e_coco.pdparams，还是出现以上的问题

**Comment by nemonameless** [comment]
您好，请拉取最新代码和换用更新paddle版本。谢谢。
