### ISSUE TITLE
训练batchsize大小问题

### ISSUE THREAD

**Issue by isLiuHao** [PaddlePaddle/PaddleYOLO#58]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我使用官方版本的yolov7代码可以batchsize=32大小训练，精度提升也很快。相同显存下，paddle的yolov7为什么batchsize只能调为8？

**Comment by nemonameless** [comment]
yolov7官方默认fp16训的，paddle里也可以，训练命令里加--amp。

**Comment by isLiuHao** [comment]
好的谢谢 我试试训练效果
