### ISSUE TITLE
ap_per_class()函数应该如何调用？

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleYOLO#62]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppdet/metrics/map_utils.py/ap_per_class()函数为啥写了但是全局都没有调用过啊
我想要统计Predicted object classes和Target object classes(在这个函数中有进行计算)
请问应该在哪里怎么调用

![image](https://user-images.githubusercontent.com/99952437/203827106-54d3450c-40c1-4f81-b2ba-7809d6bc64a2.png)

**Comment by nemonameless** [comment]
这个是从 PaddleDetection 迁移的时候遗留的，是跟踪模型JDE的检测eval指标，不同于COCO和VOC的指标。PaddleYOLO中的模型确实没用到，所以这段代码目前要删除了。

可以去PaddleDetection中使用。
如果想调用，可以在配置文件yml里加上`metric: MOTDet`覆盖掉常规的COCO或VOC的metric。
如果想单独使用，可以改代码 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/metrics/mot_metrics.py#L273  ，update函数是一张一张图计算累计的AP。
