### ISSUE TITLE
cannot download the onnx models?

### ISSUE THREAD

**Issue by coffezhou** [PaddlePaddle/PaddleYOLO#7]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

How to download the onnx models? I tried the corresponding links, but failed.

**Comment by nemonameless** [comment]
谢谢关注，服务器上在改目录和重命名。可以明天来看看，修复好了会通知您。

**Comment by nemonameless** [comment]
链接已全部更新~

**Comment by coffezhou** [comment]
Thanks! 
However, I have another question. For the model ppyoloe_crn_s_300e_coco_wo_nms.onnx, why the outputs of this model are two numbers? Without nms, I think the outputs should be two tensors with shapes of [batch, number of box, 4] and [batch, number of class, number of box]. This poblem also occures for yolov6mt_s_400e_coco_wo_nms.onnx,  yolov7_l_300e_coco_wo_nms.onnx, and yolox_s_300e_coco_wo_nms.onnx.

**Comment by nemonameless** [comment]
https://github.com/nemonameless/PaddleDetection_YOLOSeries/blob/develop/ppdet/modeling/heads/ppyoloe_head.py#L379
可以改成这样重新按命令导出一遍，其他模型也是。
```
        if self.exclude_nms:
            # `exclude_nms=True` just use in benchmark
            # return pred_bboxes.sum(), pred_scores.sum()
            return pred_bboxes, pred_scores
```

**Comment by BackT0TheFuture** [comment]
same problem.

**Comment by coffezhou** [comment]
> https://github.com/nemonameless/PaddleDetection_YOLOSeries/blob/develop/ppdet/modeling/heads/ppyoloe_head.py#L379 可以改成这样重新按命令导出一遍，其他模型也是。
> 
> ```
>         if self.exclude_nms:
>             # `exclude_nms=True` just use in benchmark
>             # return pred_bboxes.sum(), pred_scores.sum()
>             return pred_bboxes, pred_scores
> ```

Thanks for your reply! 
I have tried this method and it works.
