### ISSUE TITLE
关于anchors

### ISSUE THREAD

**Issue by YLiyu** [PaddlePaddle/PaddleYOLO#71]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的检测目标非常小，使用默认的anchors可能会有些不太合适，我想知道我们的PaddleYOLO里面有集成好的K-means方法吗？我搜索了教程里面，好像没有提到相关的配置

**Comment by nemonameless** [comment]
文档在这里：
https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/docs/tutorials/data/PrepareDetDataSet.md#%E5%8F%AF%E9%80%89%E7%94%9F%E6%88%90anchor

**Comment by YLiyu** [comment]
好的，谢谢
