### ISSUE TITLE
关于小目标评估

### ISSUE THREAD

**Issue by YLiyu** [PaddlePaddle/PaddleYOLO#73]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

训练完成以后，使用评估命令：
python tools/eval.py -c configs/yolov5/yolov5_m_300e_coco.yml -o weights=output/yolov5_m_300e_coco/best_model.pdparams

是能够正常出来评估结果，但是当我加上参数--slice_infer之后，会出现以下问题:
[12/10 11:01:26] ppdet.utils.checkpoint INFO: Finish loading model weights: ..//output/yolov5_m_300e_coco/best_model.pdparams
Traceback (most recent call last):
  File "/home/shtf/projects/PaddleYOLO-release-2.5/ppdet/engine/trainer.py", line 620, in evaluate_slice
    match_metric)
  File "/home/shtf/projects/PaddleYOLO-release-2.5/ppdet/engine/trainer.py", line 563, in _eval_with_loader_slice
    shift_amount = data['st_pix']
KeyError: 'st_pix'

出现错误的代码在trainer.py :563
shift_amount = data['st_pix'],我调试看过这个data里面有五个参数:
im_id,curr_iter,image,im_shape,scale_factor，确实似乎没有st_pix

这是我的配置文件内容:
1.configs/yolov5/yolov5_m_300e_coco.yml:
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_high.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader_high_aug.yml',
]
depth_mult: 0.67
width_mult: 0.75

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5_m_300e_coco/model_final
#pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams

TrainReader:
  batch_size: 8 # default 8 gpus, total bs = 128

YOLOv5Loss:
  obj_weight: 0.7
  cls_weght: 0.3

2.coco_detection.yml
metric: COCO
num_classes: 9

TrainDataset:
  !COCODataSet
    image_dir: train_640
    anno_path: annotations/640_train_annos_own.json
    dataset_dir: ../own_dataset
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train_annos_own.json
    dataset_dir: ../own_dataset

TestDataset:
  !ImageFolder
    anno_path: annotations/eval_annos_own.json # also support txt (like VOC's label_list.txt)
    dataset_dir: ../own_dataset # if set, anno_path will be 'dataset_dir/anno_path'

### 复现环境 Environment

环境就是按照安装文档进行安装的默认配置
Ubuntu18.04
cuda 10.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
小目标最完善的使用教程请前往 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/smalldet
ppyoloe+ 已经在众多数据集上证明过精度远超yolov5，也已经提供了基于ppyoloe的小目标优化模型。
