### ISSUE TITLE
数据增强

### ISSUE THREAD

**Issue by lyc728** [PaddlePaddle/PaddleYOLO#75]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，关于代码我有一些疑问进去请教
1、进行马赛克数据增强时，是使用4张图进行送入的，但前面是对单张图进行解码的
<img width="438" alt="企业微信截图_16715869836265" src="https://user-images.githubusercontent.com/88084847/208800707-bcd0f3d4-97d9-402f-af86-5f80ef01bf84.png">
2、进行数据增强时的sample['gt_bbox']代表什么的，传统的yolov5的数据标签应该是类别 归一化的宽高一类  麻烦解答一下，谢谢！

**Comment by nemonameless** [comment]
1. https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/ppdet/data/source/dataset.py#L82   会随机再选4张，其中3张+原图做mosaic得到新图，还有一张和新图做mixup(也可不做)。
2. https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/configs/yolov5/_base_/yolov5_reader.yml#L7 
 sample['gt_bbox']在不同transform OP后的值会发生变化，最终肯定是和原版yolov5一样的。你可以一个个OP去盯着gt_bbox看源码。

**Comment by lyc728** [comment]
> 1. https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/ppdet/data/source/dataset.py#L82   会随机再选4张，其中3张+原图做mosaic得到新图，还有一张和新图做mixup(也可不做)。
> 2. https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/configs/yolov5/_base_/yolov5_reader.yml#L7
>    sample['gt_bbox']在不同transform OP后的值会发生变化，最终肯定是和原版yolov5一样的。你可以一个个OP去盯着gt_bbox看源码。
你好，针对第一个问题，我提出的是你的数据是__getitem__进去，每次只能得到一张图，为什么做马赛克时data会是一个列表

**Comment by lyc728** [comment]
你好，这边我看到yolov5在测试时，没用到马赛克，但是有返回一个shape变量，
<img width="342" alt="企业微信截图_16718067682771" src="https://user-images.githubusercontent.com/88084847/209354263-3b70d232-4de9-46cd-a35b-bd7a2cfa50f2.png">
但是我没有看到你们代码中有这个相关的，只找到有个gt_poly
<img width="348" alt="企业微信截图_16718069134498" src="https://user-images.githubusercontent.com/88084847/209354823-698027fa-8392-433f-936f-644d7a444144.png">

**Comment by nemonameless** [comment]
1.https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/ppdet/data/source/dataset.py#L82 会随机再选4张数据组成list形式的data，`__getitem__`的那张是列表里第一张，mosaic概率为0时也会只选第一张，请仔细阅读这段代码，可以自己打断点去看下。
2. torch yolov5 eval和infer部署时 resize和reader的行为是不一致的，eval甚至是虚高的，paddleyolo里EvalReader和TestReader是一致的，按torch yolov5的infer来写的，虽然nms上还有细微的差别，但精度基本一样，https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/configs/yolov5/_base_/yolov5_reader.yml#L27  。torch yolov5 eval 虚高以及reader的行为不一致可以看以前知乎网友的讨论【如何评价Alexey Bochkovskiy团队提出的YoloV7？ - 知乎
https://www.zhihu.com/question/541985721/answer/2562541931 】

**Comment by lyc728** [comment]
> 1.https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/ppdet/data/source/dataset.py#L82 会随机再选4张数据组成list形式的data，`__getitem__`的那张是列表里第一张，mosaic概率为0时也会只选第一张，请仔细阅读这段代码，可以自己打断点去看下。 2. torch yolov5 eval和infer部署时 resize和reader的行为是不一致的，eval甚至是虚高的，paddleyolo里EvalReader和TestReader是一致的，按torch yolov5的infer来写的，虽然nms上还有细微的差别，但精度基本一样，https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/configs/yolov5/_base_/yolov5_reader.yml#L27 。torch yolov5 eval 虚高以及reader的行为不一致可以看以前知乎网友的讨论【如何评价Alexey Bochkovskiy团队提出的YoloV7？ - 知乎 https://www.zhihu.com/question/541985721/answer/2562541931 】

你好，关于torch 在进行验证时，它的数据增强是采用矩形框的形式，即采用batch进行组合和padding不同形式，返回也将shape拿出来了，而paddle我没看到类似的操作，你上面的回答跟我问题好像不一样吧
<img width="361" alt="企业微信截图_16721119582536" src="https://user-images.githubusercontent.com/88084847/209607003-6850b8cc-ad0f-4d92-9723-7941898c393a.png">

<img width="293" alt="企业微信截图_16721119479769" src="https://user-images.githubusercontent.com/88084847/209606999-3696fac8-815c-4ed2-8272-72373601492d.png">

**Comment by nemonameless** [comment]
paddle的验证和infer部署的数据增强全都是正方形，没有矩形操作，ppdet里需要让验证和部署时的reader的行为是一致的。矩形也许可以涨0.几个点的mAP，但是没啥用的，后续部署onnx等都只能640*640正方形的才可以。
