### ISSUE TITLE
加入PaddleYOLO中的指标对比图

### ISSUE THREAD

**Issue by isLinXu** [PaddlePaddle/PaddleYOLO#78]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有类似需求。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar feature requests.

### 需求描述 Feature Description

1. 任务目标 给PaddleYOLO绘制相关网络指标参数的折现对比图; 
2. 需求场景 ; 用于学术论文及实验结果的对比
3. 功能描述 目前绘图程序已经基本实现在这个[仓库](https://github.com/isLinXu/model-metrics-plot)中，后续更多模型指标参数可以一起整理验证，会以PR的形式进行提交更新

![!img](https://user-images.githubusercontent.com/59380685/212228293-3fd389cc-4f95-4df5-9ad5-e715ac8b21be.png)

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
感谢您的关注和支持，非常好的工作已star fork，欢迎给PaddleYOLO提PR，谢谢~

**Comment by isLinXu** [comment]
好的，我提交完再到这边同步一下

**Comment by isLinXu** [comment]
PR已提交，链接在：https://github.com/PaddlePaddle/PaddleYOLO/pull/79

**Comment by isLinXu** [comment]
更新在:https://github.com/PaddlePaddle/PaddleYOLO/pull/80

**Comment by nemonameless** [comment]
谢谢您的贡献。
