### ISSUE TITLE
yolov6_v20中voc/yolov6_s_40e_voc.yml文件中pretrain_weights:地址不存在

### ISSUE THREAD

**Issue by Grubby-Wang** [PaddlePaddle/PaddleYOLO#89]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

version:yolov6_v20
报错位置：../configs/voc/yolov6_s_40e_voc.yml
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/yolov6_s_400e_coco.pdparams

该预训练权重地址不存在。
![image](https://user-images.githubusercontent.com/19793717/217212742-c654cf7b-298a-4d8c-8293-e017dfbf4dcd.png)

### 复现环境 Environment

-OS: Windows10
-PaddlePaddle: 2.2.2
-PaddleYOLO: PaddleYOLO-release-2.5
-Python:3.7.4
-CUDA: 10.2
CUDNN: 7.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
https://bj.bcebos.com/v1/paddledet/models/legacy_model/yolov6_s_400e_coco.pdparams 
链接中间加个 legacy_model/, 会尽快修改。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/tree/yolov6_v20 已修复
