### ISSUE TITLE
我该使用什么版本的 paddlepaddle-gpu 

### ISSUE THREAD

**Issue by MRQinhao66666** [PaddlePaddle/PaddleYOLO#93]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在 Ubuntu 22.10  paddleyolo2.5   python3.9下  cuda11.7  gcc版本12.2.0
使用paddlepaddle-gpu2.4.1post11.7  python  tools/infer.py ... 的时候报错如下：
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)
我在paddledetect下找到解决方案降级到paddlepaddle-gpu2.3.2post11.6  解决问题，但是报另外一个错误：
 from . import core_avx
ImportError: /home/paddle/.conda/envs/paddledetect/lib/python3.9/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
我也在paddledetection的问题下找到了对应的解决方案，说是升级到paddlepaddle-gpu2.4版本就可以解决问题
可是现在问题是有两个bug 一个bug在2.3.2可以解决，另一个bug要在2.4以上解决 能否在升级版本的时候统一一下 
或者有那个版本可以解决这两个bug问题吗

**Comment by nemonameless** [comment]
from . import core_avx 报错是安装的版本没匹配上系统。你的系统环境 Ubuntu 22.10  python3.9 cuda11.7 gcc12.2.0都太高了，难免可能有版本bug遗漏。
最好安装develop版本，注意cuda版本对应就行，请查看 
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by MRQinhao66666** [comment]
我尝试了使用paddlepaddle-gpu develop版本的&nbsp;paddlepaddle-gpu-0.0.0.post117 这个版本，但是他依旧报output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:221) 这个错误

&nbsp;


耗子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleYOLO] 我该使用什么版本的 paddlepaddle-gpu  (Issue #93)





 
from . import core_avx 报错是安装的版本没匹配上系统。你的系统环境 Ubuntu 22.10  python3.9 cuda11.7 gcc12.2.0都太高了，难免可能有版本bug遗漏。
 最好安装develop版本，注意cuda版本对应就行，请查看
 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by nemonameless** [comment]
请问是哪个模型，可以提供下哪个文件的第几行代码报错吗？此外代码有改动什么地方吗？

**Comment by MRQinhao66666** [comment]
我使用的是yolov5这个模型，模型训练是在服务器上训练的，然后在我本机上进行推理测试，服务器上的paddlepaddle-gpu版本是2.3.2 使用paddlepaddle 2.4以上版本 还有develop版本都是这个报错

Traceback (most recent call last):
  File "/home/paddle/code/PaddleYOLO-release-2.5/tools/infer.py", line 232, in <module>
    main()
  File "/home/paddle/code/PaddleYOLO-release-2.5/tools/infer.py", line 228, in main
    run(FLAGS, cfg)
  File "/home/paddle/code/PaddleYOLO-release-2.5/tools/infer.py", line 189, in run
    trainer.predict(
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/engine/trainer.py", line 791, in predict
    outs = self.model(data)
  File "/home/paddle/.conda/envs/paddledetect/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/architectures/yolov5.py", line 95, in get_pred
    return self._forward()
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/architectures/yolov5.py", line 86, in _forward
    bbox, bbox_num = self.yolo_head.post_process(
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/heads/yolov5_head.py", line 195, in post_process
    bbox_pred, bbox_num, _ = self.nms(pred_bboxes, pred_scores)
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/layers.py", line 214, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "/home/paddle/code/PaddleYOLO-release-2.5/ppdet/modeling/ops.py", line 228, in multiclass_nms
    output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)

代码的话在评估阶段进行了改动，改动了ppdet/metrics/coco_utils.py 中的cocoapi_eval函数 对评估的结果的输出增加了prec和recall的计算值 改动如下：

def cocoapi_eval(jsonfile,
                 style,
                 coco_gt=None,
                 anno_file=None,
                 max_dets=(100, 300, 1000),
                 classwise=False,
                 sigmas=None,
                 use_area=True):
    """
    Args:
        jsonfile (str): Evaluation json file, eg: bbox.json, mask.json.
        style (str): COCOeval style, can be `bbox` , `segm` , `proposal`, `keypoints` and `keypoints_crowd`.
        coco_gt (str): Whether to load COCOAPI through anno_file,
                 eg: coco_gt = COCO(anno_file)
        anno_file (str): COCO annotations file.
        max_dets (tuple): COCO evaluation maxDets.
        classwise (bool): Whether per-category AP and draw P-R Curve or not.
        sigmas (nparray): keypoint labelling sigmas.
        use_area (bool): If gt annotations (eg. CrowdPose, AIC)
                         do not have 'area', please set use_area=False.
    """
    assert coco_gt != None or anno_file != None
    if style == 'keypoints_crowd':
        #please install xtcocotools==1.6
        from xtcocotools.coco import COCO
        from xtcocotools.cocoeval import COCOeval
    else:
        from pycocotools.coco import COCO
        from pycocotools.cocoeval import COCOeval

    if coco_gt == None:
        coco_gt = COCO(anno_file)
    logger.info("Start evaluate...")
    coco_dt = coco_gt.loadRes(jsonfile)
    if style == 'proposal':
        coco_eval = COCOeval(coco_gt, coco_dt, 'bbox')
        coco_eval.params.useCats = 0
        coco_eval.params.maxDets = list(max_dets)
    elif style == 'keypoints_crowd':
        coco_eval = COCOeval(coco_gt, coco_dt, style, sigmas, use_area)
    else:
        coco_eval = COCOeval(coco_gt, coco_dt, style)
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()
    if classwise:
        # Compute per-category AP and PR curve
        try:
            from terminaltables import AsciiTable
        except Exception as e:
            logger.error(
                'terminaltables not found, plaese install terminaltables. '
                'for example: `pip install terminaltables`.')
            raise e
        precisions = coco_eval.eval['precision']
        cat_ids = coco_gt.getCatIds()
        # precision: (iou, recall, cls, area range, max dets)
        assert len(cat_ids) == precisions.shape[2]
        results_per_category = []
        for idx, catId in enumerate(cat_ids):
            # area range index 0: all area ranges
            # max dets index -1: typically 100 per image
            nm = coco_gt.loadCats(catId)[0]
            precision = precisions[:, :, idx, 0, -1]
            precision = precision[precision > -1]
            if precision.size:
                ap = np.mean(precision)
            else:
                ap = float('nan')
            # results_per_category.append(
            #     (str(nm["name"]), '{:0.3f}'.format(float(ap))))
            pr_array = precisions[0, :, idx, 0, 2]
            recall_array = np.arange(0.0, 1.01, 0.01)

            # def smooth(y, f=0.05):
            #     # Box filter of fraction f
            #     nf = round(len(y) * f * 2) // 2 + 1  # number of filter elements (must be odd)
            #     p = np.ones(nf // 2)  # ones padding
            #     yp = np.concatenate((p * y[0], y, p * y[-1]), 0)  # y padded
            #     return np.convolve(yp, np.ones(nf) / nf, mode='valid')  # y-smoothed
            f1_array = 2 * pr_array * recall_array / (pr_array + recall_array + 1e-16)
            # f1_idx = smooth(f1_array, 0.1).argmax()
            f1_idx = f1_array.argmax()
            p, r, f1 = pr_array[f1_idx], recall_array[f1_idx], f1_array[f1_idx]
            results_per_category.append((str(nm["name"]), '{:0.3f}'.format(float(p)), '{:0.3f}'.format(float(r)),
                                         '{:0.3f}'.format(float(f1)), '{:0.3f}'.format(float(ap))))
            draw_pr_curve(
                pr_array,
                recall_array,
                out_dir=style + '_pr_curve',
                file_name='{}_precision_recall_curve.jpg'.format(nm["name"]))

        # num_columns = min(6, len(results_per_category) * 2)
        num_columns = min(6, len(results_per_category) * 5)
        results_flatten = list(itertools.chain(*results_per_category))
        # headers = ['category', 'AP'] * (num_columns // 2)
        headers = ['category', 'P', 'R', 'F1', 'AP'] * (num_columns // 5)
        results_2d = itertools.zip_longest(
            *[results_flatten[i::num_columns] for i in range(num_columns)])
        table_data = [headers]
        table_data += [result for result in results_2d]
        table = AsciiTable(table_data)
        logger.info('Per-category of {} AP: \n{}'.format(style, table.table))
        logger.info("per-category PR curve has output to {} folder.".format(
            style + '_pr_curve'))
    # flush coco evaluation result
    sys.stdout.flush()
    return coco_eval.stats




 
请问是哪个模型，可以提供下哪个文件的第几行代码报错吗？此外代码有改动什么地方吗？

**Comment by nemonameless** [comment]
`output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,` 你在`ppdet/modeling/ops.py`报错的这行代码是过时的，建议之后提问的时候就可以先描述清楚点。和后面改cocoapi_eval没有关系。
https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.5 确定代码是最新代码吗？可以拉取最新2.5 2.6或develop的代码再试试。
如果系统里有安装了paddledet建议先卸载再重装`python setup.py install`，其实不安装也是可以用的。

**Comment by nemonameless** [comment]
#64 #25

**Comment by MRQinhao66666** [comment]
谢谢，我升级到paddleyolo2.6版本后解决了该问题


> `output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,` 你在`ppdet/modeling/ops.py`报错的这行代码是过时的，建议之后提问的时候就可以先描述清楚点。和后面改cocoapi_eval没有关系。 https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.5 确定代码是最新代码吗？可以拉取最新2.5 2.6或develop的代码再试试。 如果系统里有安装了paddledet建议先卸载再重装`python setup.py install`，其实不安装也是可以用的。
